"""LANE-B / MOB-LOOT-001: the monster a player kills leaves something behind.

WHAT THIS MODULE IS FOR.  M5 is "loot drops, you pick it up, it is in your bag
after a relog".  This module is its FIRST half and says so in every claim it
makes: a kill rolls the dead monster's OWN drop sets out of the real game
tables, the roll becomes a ledger of objects standing at the place it fell, and
each object becomes one frame of the exact list shape an attended run has
already seen the client draw.  What it does NOT do is the second half: nothing
here picks anything up, and nothing here writes a database row.  The two halves
are separated at the ledger on purpose -- the pickup side's trigger is a client
message this project has never seen on the wire (see NONCLAIMS 4), and mixing
a proven half with an unproven one inside one round is how a lane ends up
claiming both.

    roll      <- the dead mob's own DROPS_NORMAL / _EQUIPMENT / _SPECIALLY
    ledger    <- what is standing on the ground, where, and whose kill made it
    element   <- one RuntimeRes derived-bit-0x08 list element per object
    frame     <- one single-element frame each (the V43 one-record lesson)

NO FLAG, AND THAT IS THE POINT.  ``production_allowed`` is True.  There is no
scenario id, no dispatch kwarg, no unlock object and no allowlisted profile in
this file.  The lane that PROVED the wire shape (``ground_loot_hypothesis``,
HYP-PF-032) is a scenario-gated probe that can only ever emit its own two
hard-coded elements at scene load; a build the owner boots with no flags cannot
reach one byte of it.  So the encoder is RE-DERIVED here, in general form, from
the same static anchors, and ``tests/test_mob_loot.py`` pins the composed bytes
against that probe lane's own encoder, element for element.  This module
imports NO probe lane.

WHAT THE PLAYER SEES, AND FOR HOW LONG.  The one attended measurement of this
pipe (GT-045 job 1135, 2026-08-25, and GT-045 v3 jobs 1122-1124) is precise
about both halves of that question:

  * [MEASURED] An element whose payload dword was 2200423 drew a MODEL and a
    floating NAME LABEL on the ground at the coordinate the server sent.  An
    element whose payload dword was 2600001 drew DUST and no model and no
    name.  The difference between those two ids in the tables is
    ``n_DROPMODEL_TYPE`` (nonzero vs zero) and nothing else this lane can see.
  * [MEASURED, and it is a refutation of our own prediction] Nothing stays.
    The observer walked onto both coordinates afterwards and swept the camera:
    no object.  The frame measurement of 2026-08-23 gives the scale -- a loot
    object stood for 0.633 s.  ``GROUND_DROP_DOES_NOT_PERSIST`` is therefore a
    CONSTANT of this module, not a caveat in a paragraph.

So the honest sentence for this round is "the monster you killed leaves ITS OWN
loot, named, where it fell, for about half a second".  Not "you can pick it
up".  :func:`refresh_frames` exists so a caller CAN re-emit the ledger on a
cadence, which is the only thing this lane can offer toward "it stays"; whether
re-emission keeps the object drawn is UNMEASURED and is written as a nonclaim
rather than as a feature.

PROVENANCE OF EVERY CLAIM THE CODE MAKES
----------------------------------------
* [STATIC, survived adversarial re-derive in GT-042] The 0x5F85B0 element
  shape: key (tag 0x14 u32, +0x10), dirty mask (tag 0x0B, +0x28), then per
  mask bit in order -- 0x02 -> tag 0x14 u32 (+0x14), 0x04 -> tag 0x0F u16
  (+0x18), 0x08 -> tag 0x05 u8 (+0x1B), 0x10 -> three tag 0x2A f32 (+0x1C,
  +0x20, +0x24), 0x20 -> tag 0x08 u8 (+0x1A).  This lane emits mask 0x12 --
  position and the payload dword -- which is the ONE combination that has
  been on a real client's wire.
* [STATIC] The envelope is the proven RuntimeRes v4 envelope, with the derived
  change-mask byte 0x08 selecting the list, and ONE element per frame: a
  combined multi-record derived-mask collection is the one shape a real client
  has already rejected with ErrorData=28317.
* [MEASURED, committed tables] Every rate, weight, quantity span and item id
  comes from ``field_drop_tables``, generated by
  ``tools/pf_mine_scene_drop_tables.py`` from the committed CONSTDATA tables
  with four controls it refuses on; the set-id rule ``prefix * 100000 + n_ID``
  is the round-100 fact pack's, verified there on the full data.
* [OUR DESIGN] The ROLL ORDER, the meaning of a percentage rate, the map from
  a uniform draw to a quantity, the cumulative-threshold weighted walk and the
  with-replacement multi-pick are ours -- the original server's roll order and
  RNG are unrecoverable forever.  They are deliberately IDENTICAL to
  ``loot_roll``'s three primitives, and ``tests/test_mob_loot.py`` pins them
  against that module value by value so the project has one roll semantics and
  not two.  (This module does not IMPORT ``loot_roll``: that module states as
  part of its own contract that nothing in ``src/`` imports it and that it is
  unreachable from production dispatch, and a production import would make its
  own docstring false.)
* [OUR DESIGN] The ground layout: object N of a kill stands at the death
  position offset by ``DROP_SCATTER_STEP`` * N on X.  30.0 units is the only
  offset any attended run has confirmed lands where a player standing at the
  reference point can see it.
* [OUR DESIGN] The element key block.  The list's key space has no proven
  allocation rule anywhere in this project; this lane allocates from
  ``DROP_KEY_BASE`` upward so its keys cannot collide with the only two keys
  anyone here has ever sent (1 and 2) or with the actor identity range this
  scene's monsters use (0x2000..0x20FF), and refuses any key outside its own
  block.

WHAT THIS MODULE IS NOT.  PURE SERVER LOGIC WITH ONE COMPOSER.  It opens no
socket, touches no database, boots no server, reads no file, keeps no global
state, calls no clock and never touches the module-global ``random`` (the
caller injects a ``random.Random``; see DETERMINISM).  Importing it has no side
effects.

DETERMINISM.  Every stochastic decision is a draw from an INJECTED
``random.Random``, taken through ``rng.random()`` and nothing else.  Same
tables + same mob + same seed produce identical results in any process, and
the draw stream does not depend on whether a row decodes: a slot that wins its
rate roll consumes its quantity draw even when its item id is then refused.

THE LINE THIS LANE NEEDS FROM THE CHIEF is :data:`MOB_LOOT_WIRING`.  It is one
call after the death frames of ``mob_death``, and it is written there rather
than only in a letter, because letters get lost.
"""

from __future__ import annotations

from dataclasses import dataclass
import hashlib
import math
import struct
from typing import Any

from . import field_drop_tables
from .field_mobs import FieldMob


MOB_LOOT_MILESTONE = "MOB-LOOT-001"
MOB_LOOT_BUILD_ORDER = "BUILD-006 / M5 first half"
MOB_LOOT_LANE = "B_COMBAT"

MOB_LOOT_WIRING = (
    "runtime.py, immediately after the death frames of MOB-DEATH-001 for a "
    "kill that commit_death() ACCEPTED (a rejected compare-and-swap must not "
    "roll loot -- the monster it names is already dead and already looted):\n"
    "  1. roll = mob_loot.roll_drops(mob, rng)          # rng is the server's\n"
    "  2. drops = mob_loot.place_drops(mob, record, roll, ledger.next_key, "
    "position=<where it fell, or None for its placement position>)\n"
    "  3. ledger_next = mob_loot.commit_drops(ledger_now, drops)   # CAS; a "
    "rejected commit means retry from step 2 with the fresh ledger, NOT "
    "re-roll (re-rolling gives the player a second roll for one kill)\n"
    "  4. send every frame of mob_loot.drop_frames(legacy, drops) AFTER the "
    "dying frame, one frame each, in the order returned\n"
    "  5. nothing else: there is no pickup half yet, and the objects are gone "
    "from the screen in about half a second (GROUND_DROP_DOES_NOT_PERSIST).  "
    "If you want to try holding them, mob_loot.refresh_frames(legacy, ledger) "
    "re-emits the live ledger and DROP_REFRESH_MS is our unmeasured guess at "
    "the cadence; that is an experiment, not a shipped behaviour."
)

production_allowed = True
test_only = False

# ---------------------------------------------------------------------------
# Wire pins.  Every value here is cross-pinned in tests against the probe lane
# that measured it; none of them is chosen by this module.
# ---------------------------------------------------------------------------
RUNTIME_DERIVED_BIT_GROUND_LIST = 0x08   # derived change-mask -> object +0x20
ELEMENT_MASK_POSITION_AND_DWORD = 0x12   # 0x10 position | 0x02 dword at +0x14
ELEMENT_KEY_TAG = 0x14                   # +0x10, always on the wire
ELEMENT_MASK_TAG = 0x0B                  # +0x28 dirty mask
ELEMENT_PAYLOAD_TAG = 0x14               # +0x14, mask bit 0x02
ELEMENT_F32_TAG = 0x2A                   # +0x1C / +0x20 / +0x24
ELEMENT_LIST_COUNT_TAG = 0x12
ENVELOPE_VERSION = 4
DROP_PC_SIZE = 44                        # one element, pinned by GT-045
DROP_FRAME_SIZE = 54                     # the same pc, framed
DROP_COORD_SPANS = ((30, 34), (35, 39), (40, 44))
DROP_FRAME_COORD_SHIFT = 10

# The list codec's element field order, re-derived from the same span
# [0x005F85B0,0x005F8869) sha256 ce0a58f7.. that GT-040/GT-042 pinned.
ELEMENT_FIELD_ORDER = (
    "key_u32_tag14",
    "dirty_mask_u8_tag0B",
    "payload_u32_tag14",
    "x_f32_tag2A",
    "y_f32_tag2A",
    "z_f32_tag2A",
)

# ---------------------------------------------------------------------------
# Lane constants that are OURS.  Each one is named so a reader can see it is a
# decision, and each is repeated in MOB_LOOT_NONCLAIMS if it is unmeasured.
# ---------------------------------------------------------------------------
DROP_KEY_BASE = 0x00100000
DROP_KEY_LIMIT = 0x00200000
DROP_SCATTER_STEP = 30.0
DROP_REFRESH_MS = 500
MAX_DROPS_PER_KILL = 16

# [MEASURED, GT-045 v3 jobs 1122-1124 + the 2026-08-23 frame measurement]
GROUND_DROP_DOES_NOT_PERSIST = True
GROUND_DROP_OBSERVED_LIFETIME_SECONDS = 0.633

# The money slot: ``n_ITEM = 0`` with a nonzero rate.  [INFERENCE] in the
# round-100 fact pack, [INFERENCE] here, and it can never reach the ground
# through this pipe -- the element's only content field is an ITEM ID, so a
# money drop has nothing to put in it.  Rolled and recorded, never emitted.
MONEY_ITEM_ID = 0
MONEY_TAG = "INFERENCE_MONEY_SLOT"

SOURCE_TABLE_NORMAL = "DROPS_NORMAL"
SOURCE_TABLE_EQUIPMENT = "DROPS_EQUIPMENT"
SOURCE_TABLE_SPECIALLY = "DROPS_SPECIALLY"
SOURCE_TABLES = (
    SOURCE_TABLE_NORMAL, SOURCE_TABLE_EQUIPMENT, SOURCE_TABLE_SPECIALLY,
)

_FLOAT32_MAX = 3.4028235e38

MOB_LOOT_NONCLAIMS = (
    "1. Nothing dispatches this module.  runtime.py is the chief's file and "
    "MOB_LOOT_WIRING is a request, not a call site.  No player has seen one "
    "byte of this lane.",
    "2. The objects DO NOT STAY.  The only attended run of this pipe measured "
    "0.633 s and then nothing on the ground at either coordinate.  This lane "
    "makes loot APPEAR; it does not make it lie there waiting.",
    "3. The client has never been shown a drop element for an id this lane "
    "chose.  Two ids have ever travelled (2200423 and 2600001) and both were "
    "hard-coded by the probe lane.  That a rolled id renders like 2200423 is "
    "an EXPECTATION from one column (n_DROPMODEL_TYPE), not a measurement.",
    "4. There is no pickup.  The only proven PickupTerrainThing producer is "
    "client-outbound (GT-046) and its vital id is hash-DERIVED (0x4543), never "
    "observed; the corpus holds zero frames of it in either direction.  The "
    "ledger exists so the pickup half has somewhere to look up a key -- it is "
    "not evidence that a key can be picked up.",
    "5. Ownership is bookkeeping only.  ``killer_identity`` is recorded "
    "because the second half will need it; the element has no owner field, so "
    "nothing on the wire enforces who may take a drop.",
    "6. The quantity never reaches the client.  The element carries an item "
    "id and a position and nothing else, so a stack of five is drawn -- if it "
    "is drawn at all -- exactly like a stack of one.  The count lives in the "
    "ledger for the pickup half.",
    "7. Money cannot be placed.  A money slot has no item id, and the "
    "element's only content field is one.  Rolled, recorded, never emitted -- "
    "and the reading that item id 0 means money is [INFERENCE], not proven.",
    "8. DROPS_QUEST is refused by name, table and all: only 311 of the 2478 "
    "DROPS_QUEST sets the mobs reference exist client-side.",
    "9. Item quality is not rolled.  E_DROPS_QUALITY exists and "
    "``loot_roll`` implements it, but the element has nowhere to carry a "
    "quality, so rolling one here would produce a number no player could ever "
    "see.  The pickup half, which puts items in a bag, is where that belongs.",
    "10. The ledger lives in the caller's process.  Nothing in this project "
    "persists a ground object across a restart, and this module writes no "
    "database row.",
    "11. The element key block is ours and unproven.  Nobody has shown what "
    "the client does with a key it has never seen, or whether that key space "
    "is shared with anything else.",
    "12. Whether re-emitting an element keeps the object on screen is "
    "UNMEASURED.  ``refresh_frames`` composes the frames; DROP_REFRESH_MS is "
    "a guess; re-emission may equally restart the drop effect each time.",
)

# ---------------------------------------------------------------------------
# Refusals.  A refusal has a NAME, and every name here is reachable: a name
# that cannot happen is a lie to whoever counts them (the rule mob_combat
# wrote for itself when its floor moved).
# ---------------------------------------------------------------------------
REFUSE_TYPE_NOT_TYPED_RECORD = "type_not_typed_record"
REFUSE_VALUE_NOT_INT = "value_not_int"
REFUSE_VALUE_OUT_OF_RANGE = "value_out_of_range"
REFUSE_IDENTITY_NOT_POSITIVE = "identity_not_positive"
REFUSE_POSITION_NOT_FINITE = "position_not_finite"
REFUSE_RNG_HAS_NO_RANDOM = "rng_has_no_random"
REFUSE_DRAW_OUT_OF_UNIT_INTERVAL = "draw_out_of_unit_interval"
REFUSE_QUANTITY_RANGE_INVERTED = "quantity_range_inverted"
REFUSE_UNKNOWN_DROP_SET = "unknown_drop_set"
REFUSE_UNKNOWN_ITEM_ID = "unknown_item_id"
REFUSE_ROLL_NAMES_ANOTHER_MONSTER = "roll_names_another_monster"
REFUSE_KEY_OUTSIDE_THE_LANE_BLOCK = "key_outside_the_lane_block"
REFUSE_LEDGER_NOT_SORTED = "ledger_not_sorted"
REFUSE_DUPLICATE_LEDGER_KEY = "duplicate_ledger_key"
REFUSE_LEDGER_STALE = "ledger_stale"
REFUSE_DROP_NOT_IN_LEDGER = "drop_not_in_ledger"
REFUSE_TOO_MANY_DROPS_FOR_ONE_KILL = "too_many_drops_for_one_kill"
REFUSE_MONEY_HAS_NO_ELEMENT = "money_has_no_element"
REFUSE_COMPOSED_BYTES_OFF_PIN = "composed_bytes_off_pin"
REFUSE_ELEMENT_ENCODER_DISAGREES = "element_encoder_disagrees"
REFUSE_POSITION_OFF_THE_F32_GRID = "position_off_the_f32_grid"

MOB_LOOT_REFUSAL_REASONS = (
    REFUSE_TYPE_NOT_TYPED_RECORD,
    REFUSE_VALUE_NOT_INT,
    REFUSE_VALUE_OUT_OF_RANGE,
    REFUSE_IDENTITY_NOT_POSITIVE,
    REFUSE_POSITION_NOT_FINITE,
    REFUSE_RNG_HAS_NO_RANDOM,
    REFUSE_DRAW_OUT_OF_UNIT_INTERVAL,
    REFUSE_QUANTITY_RANGE_INVERTED,
    REFUSE_UNKNOWN_DROP_SET,
    REFUSE_UNKNOWN_ITEM_ID,
    REFUSE_ROLL_NAMES_ANOTHER_MONSTER,
    REFUSE_KEY_OUTSIDE_THE_LANE_BLOCK,
    REFUSE_LEDGER_NOT_SORTED,
    REFUSE_DUPLICATE_LEDGER_KEY,
    REFUSE_LEDGER_STALE,
    REFUSE_DROP_NOT_IN_LEDGER,
    REFUSE_TOO_MANY_DROPS_FOR_ONE_KILL,
    REFUSE_MONEY_HAS_NO_ELEMENT,
    REFUSE_COMPOSED_BYTES_OFF_PIN,
    REFUSE_ELEMENT_ENCODER_DISAGREES,
    REFUSE_POSITION_OFF_THE_F32_GRID,
)


class MobLootContractError(ValueError):
    """Every refusal in this module, carrying its reason NAME as args[0]."""


def _require_int(value: Any, label: str, minimum: int, maximum: int) -> int:
    if type(value) is not int or type(value) is bool:
        raise MobLootContractError(
            REFUSE_VALUE_NOT_INT, "%s must be an int" % label)
    if not minimum <= value <= maximum:
        raise MobLootContractError(
            REFUSE_VALUE_OUT_OF_RANGE,
            "%s must be in [%d, %d], got %d" % (label, minimum, maximum, value))
    return value


def _require_identity(value: Any, label: str) -> int:
    identity = _require_int(value, label, -(2 ** 62), 2 ** 62)
    if identity <= 0:
        raise MobLootContractError(
            REFUSE_IDENTITY_NOT_POSITIVE, "%s must be positive" % label)
    return identity


def _require_float32(value: Any, label: str) -> float:
    if type(value) not in (int, float) or type(value) is bool:
        raise MobLootContractError(
            REFUSE_POSITION_NOT_FINITE, "%s must be a finite number" % label)
    result = float(value)
    if not math.isfinite(result) or abs(result) > _FLOAT32_MAX:
        raise MobLootContractError(
            REFUSE_POSITION_NOT_FINITE, "%s must be finite float32" % label)
    return result


def as_wire_float(value: float) -> float:
    """Quantize to the exact f32 the wire will carry."""
    return struct.unpack("<f", struct.pack("<f", float(value)))[0]


def _require_draw(draw: Any) -> float:
    if type(draw) not in (int, float) or type(draw) is bool:
        raise MobLootContractError(
            REFUSE_DRAW_OUT_OF_UNIT_INTERVAL, "a draw must be a number")
    value = float(draw)
    if not math.isfinite(value) or not 0.0 <= value < 1.0:
        raise MobLootContractError(
            REFUSE_DRAW_OUT_OF_UNIT_INTERVAL,
            "a draw must be in [0.0, 1.0), got %r" % (draw,))
    return value


def _require_rng(rng: Any) -> Any:
    if not hasattr(rng, "random") or not callable(rng.random):
        raise MobLootContractError(
            REFUSE_RNG_HAS_NO_RANDOM,
            "roll_drops needs an injected random.Random; this lane never "
            "touches the module-global random")
    return rng


def _require_mob(mob: Any) -> FieldMob:
    if type(mob) is not FieldMob:
        raise MobLootContractError(
            REFUSE_TYPE_NOT_TYPED_RECORD,
            "this lane rolls for a typed FieldMob roster row, not a dict")
    return mob


# ---------------------------------------------------------------------------
# The three primitives.  Identical in semantics to loot_roll's, pinned against
# them value by value in the tests, and re-derived here so that a production
# module does not import a module whose contract says nothing in src/ does.
# ---------------------------------------------------------------------------
def rate_succeeds(rate_percent: float, draw: float) -> bool:
    """``draw < rate / 100``: 0 pct never fires, 100 pct always fires.

    The comparison is strict, so an entry EXACTLY AT the threshold fails: for
    a 0.5 pct rate the threshold is 0.005 and a draw of 0.005 does not drop.
    """
    return _require_draw(draw) < float(rate_percent) / 100.0


def uniform_quantity(low: int, high: int, draw: float) -> int:
    """A flat integer span: ``low + int(draw * (high - low + 1))``, clamped."""
    span = high - low + 1
    if span <= 0:
        raise MobLootContractError(
            REFUSE_QUANTITY_RANGE_INVERTED,
            "quantity range is inverted: %d..%d" % (low, high))
    value = low + int(_require_draw(draw) * span)
    if value < low:
        return low
    if value > high:
        return high
    return value


def weighted_pick(weights: Any, draw: float) -> int | None:
    """Cumulative-threshold walk in TABLE ORDER; ``None`` if no positive total.

    The chosen index is the FIRST whose running sum strictly EXCEEDS
    ``draw * total``, so a zero-weight entry owns an empty interval and can
    never be picked, and the total is the ACTUAL sum rather than an assumed
    100.
    """
    target_draw = _require_draw(draw)
    total = 0
    for weight in weights:
        total += int(weight)
    if total <= 0:
        return None
    target = target_draw * total
    cumulative = 0
    for index, weight in enumerate(weights):
        cumulative += int(weight)
        if cumulative > target:
            return index
    return len(weights) - 1


# ---------------------------------------------------------------------------
# What a roll produces.
# ---------------------------------------------------------------------------
@dataclass(frozen=True)
class DropItem:
    """One item a kill produced: what, how many, and which table said so."""

    item_id: int
    quantity: int
    source_table: str
    source_set_id: int
    source_index: int

    def __post_init__(self) -> None:
        _require_int(self.item_id, "item id", 1, 0xFFFFFFFF)
        _require_int(self.quantity, "quantity", 1, 0xFFFF)
        if self.source_table not in SOURCE_TABLES:
            raise MobLootContractError(
                REFUSE_TYPE_NOT_TYPED_RECORD,
                "source table must be one of %s" % (SOURCE_TABLES,))
        _require_int(self.source_set_id, "source set id", 1, 0xFFFFFFFF)
        _require_int(self.source_index, "source index", 1, 0xFF)
        if self.item_id not in field_drop_tables.ITEMS:
            raise MobLootContractError(
                REFUSE_UNKNOWN_ITEM_ID,
                "item %d is not in the mined item table" % self.item_id)

    @property
    def display_name(self) -> str:
        return field_drop_tables.ITEMS[self.item_id][2]

    @property
    def drop_model_type(self) -> int:
        """The column that separated the two attended runs.  NOT a claim."""
        return field_drop_tables.ITEMS[self.item_id][3]


@dataclass(frozen=True)
class MoneyDrop:
    """A money slot that won its rate roll.  It can never reach the ground."""

    amount: int
    source_table: str
    source_set_id: int
    source_index: int
    tag: str = MONEY_TAG

    def __post_init__(self) -> None:
        _require_int(self.amount, "amount", 1, 0xFFFFFFFF)
        if self.source_table not in SOURCE_TABLES:
            raise MobLootContractError(
                REFUSE_TYPE_NOT_TYPED_RECORD,
                "source table must be one of %s" % (SOURCE_TABLES,))
        _require_int(self.source_set_id, "source set id", 1, 0xFFFFFFFF)
        _require_int(self.source_index, "source index", 1, 0xFF)
        if self.tag != MONEY_TAG:
            raise MobLootContractError(
                REFUSE_TYPE_NOT_TYPED_RECORD,
                "a money drop keeps its inference tag")


@dataclass(frozen=True)
class DropRoll:
    """Everything one kill produced, and everything it refused."""

    mob_template_id: int
    mob_identity: int
    items: tuple
    money: tuple
    draws: int
    refusals: tuple

    def __post_init__(self) -> None:
        _require_int(self.mob_template_id, "template id", 1, 0xFFFFFFFF)
        _require_identity(self.mob_identity, "mob identity")
        for item in self.items:
            if type(item) is not DropItem:
                raise MobLootContractError(
                    REFUSE_TYPE_NOT_TYPED_RECORD,
                    "every rolled item must be a typed DropItem")
        for money in self.money:
            if type(money) is not MoneyDrop:
                raise MobLootContractError(
                    REFUSE_TYPE_NOT_TYPED_RECORD,
                    "every money row must be a typed MoneyDrop")
        _require_int(self.draws, "draw count", 0, 0xFFFF)

    @property
    def placeable_count(self) -> int:
        """How many of these can actually stand on the ground."""
        return len(self.items)


def _set_rows(mob: FieldMob) -> tuple:
    """The three drop sets of one roster row, refusing an unmined one."""
    rows = []
    for set_id, table, source in (
        (mob.drops_normal, field_drop_tables.DROPS_NORMAL,
         SOURCE_TABLE_NORMAL),
        (mob.drops_equipment, field_drop_tables.DROPS_EQUIPMENT,
         SOURCE_TABLE_EQUIPMENT),
        (mob.drops_specially, field_drop_tables.DROPS_SPECIALLY,
         SOURCE_TABLE_SPECIALLY),
    ):
        if set_id == 0:
            continue
        if set_id not in table:
            raise MobLootContractError(
                REFUSE_UNKNOWN_DROP_SET,
                "%s set %d is not in the mined tables; regenerate "
                "field_drop_tables rather than patch it"
                % (source, set_id))
        rows.append((source, set_id, table[set_id]))
    return tuple(rows)


def _roll_normal(set_id, row, rng, items, money, refusals) -> int:
    """Per-slot independent percentage rates, in table order."""
    draws = 0
    for index, item_id, rate, low, high in row:
        draws += 1
        if not rate_succeeds(rate, rng.random()):
            continue
        # The quantity draw is consumed whether or not the id resolves, so the
        # stream does not depend on the tables' contents.
        draws += 1
        quantity_draw = rng.random()
        if low > high:
            refusals.append((REFUSE_QUANTITY_RANGE_INVERTED, set_id, index))
            continue
        quantity = uniform_quantity(low, high, quantity_draw)
        if quantity <= 0:
            refusals.append((REFUSE_VALUE_OUT_OF_RANGE, set_id, index))
            continue
        if item_id == MONEY_ITEM_ID:
            money.append(MoneyDrop(
                quantity, SOURCE_TABLE_NORMAL, set_id, index))
            continue
        if item_id not in field_drop_tables.ITEMS:
            refusals.append((REFUSE_UNKNOWN_ITEM_ID, set_id, index))
            continue
        items.append(DropItem(
            item_id, quantity, SOURCE_TABLE_NORMAL, set_id, index))
    return draws


def _roll_weighted(source, set_id, row, rng, items, money, refusals) -> int:
    """One roll at the set rate, then that many weighted picks."""
    rate, number_min, number_max, entries = row
    draws = 1
    if not rate_succeeds(rate, rng.random()):
        return draws
    draws += 1
    count_draw = rng.random()
    if number_min > number_max:
        refusals.append((REFUSE_QUANTITY_RANGE_INVERTED, set_id, 0))
        return draws
    count = uniform_quantity(number_min, number_max, count_draw)
    weights = [weight for _index, _item, weight in entries]
    for _pick in range(count):
        draws += 1
        chosen = weighted_pick(weights, rng.random())
        if chosen is None:
            refusals.append((REFUSE_VALUE_OUT_OF_RANGE, set_id, 0))
            continue
        index, item_id, _weight = entries[chosen]
        if item_id == MONEY_ITEM_ID:
            money.append(MoneyDrop(1, source, set_id, index))
            continue
        if item_id not in field_drop_tables.ITEMS:
            refusals.append((REFUSE_UNKNOWN_ITEM_ID, set_id, index))
            continue
        items.append(DropItem(item_id, 1, source, set_id, index))
    return draws


def roll_drops(mob: Any, rng: Any) -> DropRoll:
    """Roll one dead monster's OWN drop sets, in table order.

    ``rng`` is an injected ``random.Random``.  The order is DROPS_NORMAL (per
    slot), then DROPS_EQUIPMENT, then DROPS_SPECIALLY -- OUR order, taken from
    the column order of the MOBS row itself, because the original server's is
    unrecoverable.
    """
    mob = _require_mob(mob)
    rng = _require_rng(rng)
    items: list = []
    money: list = []
    refusals: list = []
    draws = 0
    for source, set_id, row in _set_rows(mob):
        if source == SOURCE_TABLE_NORMAL:
            draws += _roll_normal(set_id, row, rng, items, money, refusals)
        else:
            draws += _roll_weighted(
                source, set_id, row, rng, items, money, refusals)
    return DropRoll(
        mob.template_id, mob.actor_identity, tuple(items), tuple(money),
        draws, tuple(refusals),
    )


# ---------------------------------------------------------------------------
# What stands on the ground.
# ---------------------------------------------------------------------------
@dataclass(frozen=True)
class GroundDrop:
    """One object standing where a monster fell."""

    drop_key: int
    item_id: int
    quantity: int
    x: float
    y: float
    z: float
    mob_identity: int
    killer_identity: int

    def __post_init__(self) -> None:
        _require_int(self.drop_key, "drop key", 0, 0xFFFFFFFF)
        if not DROP_KEY_BASE <= self.drop_key < DROP_KEY_LIMIT:
            raise MobLootContractError(
                REFUSE_KEY_OUTSIDE_THE_LANE_BLOCK,
                "drop key 0x%X is outside this lane's block [0x%X, 0x%X)"
                % (self.drop_key, DROP_KEY_BASE, DROP_KEY_LIMIT))
        _require_int(self.item_id, "item id", 1, 0xFFFFFFFF)
        _require_int(self.quantity, "quantity", 1, 0xFFFF)
        for label, value in (("x", self.x), ("y", self.y), ("z", self.z)):
            coordinate = _require_float32(value, label)
            if coordinate != as_wire_float(coordinate):
                raise MobLootContractError(
                    REFUSE_POSITION_OFF_THE_F32_GRID,
                    "%s is not an exact f32; quantize before building a drop"
                    % label)
        _require_identity(self.mob_identity, "mob identity")
        _require_identity(self.killer_identity, "killer identity")
        if self.mob_identity == self.killer_identity:
            raise MobLootContractError(
                REFUSE_ROLL_NAMES_ANOTHER_MONSTER,
                "a monster cannot loot itself on this lane")
        if self.item_id not in field_drop_tables.ITEMS:
            raise MobLootContractError(
                REFUSE_UNKNOWN_ITEM_ID,
                "item %d is not in the mined item table" % self.item_id)

    @property
    def display_name(self) -> str:
        return field_drop_tables.ITEMS[self.item_id][2]


@dataclass(frozen=True)
class DropLedger:
    """What is on the ground, as a tuple sorted by key.

    Sorted-tuple with a ``generation`` for the reason ``DeathRegister`` has
    one: a ledger is a VALUE, so "add a drop" is a read-modify-write of
    something nobody owns.  Two kills in the same tick both read the same
    ledger, both return a ledger of their own drops, and whichever is stored
    second erases the other kill's loot with nothing raised anywhere.
    :func:`commit_drops` is the compare-and-swap that makes the loser retry.
    """

    drops: tuple = ()
    generation: int = 0

    def __post_init__(self) -> None:
        if type(self.drops) is not tuple:
            raise MobLootContractError(
                REFUSE_TYPE_NOT_TYPED_RECORD, "drops must be a tuple")
        seen = set()
        for drop in self.drops:
            if type(drop) is not GroundDrop:
                raise MobLootContractError(
                    REFUSE_TYPE_NOT_TYPED_RECORD,
                    "every ledger row must be a typed GroundDrop")
            if drop.drop_key in seen:
                raise MobLootContractError(
                    REFUSE_DUPLICATE_LEDGER_KEY,
                    "drop key 0x%X appears twice" % drop.drop_key)
            seen.add(drop.drop_key)
        ordered = tuple(sorted(self.drops, key=lambda row: row.drop_key))
        if ordered != self.drops:
            raise MobLootContractError(
                REFUSE_LEDGER_NOT_SORTED,
                "ledger rows must be given in ascending key order")
        _require_int(self.generation, "generation", 0, 2 ** 62)

    @property
    def next_key(self) -> int:
        """The key a new drop may take.  Refuses when the block is spent."""
        if not self.drops:
            return DROP_KEY_BASE
        candidate = self.drops[-1].drop_key + 1
        if candidate >= DROP_KEY_LIMIT:
            raise MobLootContractError(
                REFUSE_KEY_OUTSIDE_THE_LANE_BLOCK,
                "this lane's key block is spent; nothing reuses a key while "
                "the client may still hold it")
        return candidate

    def get(self, drop_key: int) -> GroundDrop:
        for drop in self.drops:
            if drop.drop_key == drop_key:
                return drop
        raise MobLootContractError(
            REFUSE_DROP_NOT_IN_LEDGER,
            "no drop with key 0x%X is on the ground" % drop_key)


def place_drops(
    mob: Any,
    record: Any,
    roll: DropRoll,
    first_key: int,
    position: Any = None,
) -> tuple:
    """Turn a roll into the objects that stand where the monster fell.

    ``record`` is the ``mob_death.DeathRecord`` of the kill -- taken as a duck
    type on purpose so this module does not import the death lane just to read
    two identities off it, but its identities MUST agree with the roll.

    ``position`` is where it fell.  ``None`` means the roster placement
    position, which is a fallback and not a truth: a monster that chased a
    player died somewhere else, and this lane has no live position of its own.

    Object N stands at position + ``DROP_SCATTER_STEP`` * N on X so two drops
    of one kill are not one object at one point.  Money is not placed: see
    NONCLAIM 7.
    """
    mob = _require_mob(mob)
    if type(roll) is not DropRoll:
        raise MobLootContractError(
            REFUSE_TYPE_NOT_TYPED_RECORD, "roll must be a typed DropRoll")
    actor_identity = _require_identity(
        getattr(record, "actor_identity", None), "record actor identity")
    killer_identity = _require_identity(
        getattr(record, "killer_identity", None), "record killer identity")
    if actor_identity != roll.mob_identity or actor_identity != mob.actor_identity:
        raise MobLootContractError(
            REFUSE_ROLL_NAMES_ANOTHER_MONSTER,
            "the death record, the roll and the roster row must name one "
            "monster: 0x%X, 0x%X, 0x%X"
            % (actor_identity, roll.mob_identity, mob.actor_identity))
    _require_int(first_key, "first key", 0, 0xFFFFFFFF)
    if not DROP_KEY_BASE <= first_key < DROP_KEY_LIMIT:
        raise MobLootContractError(
            REFUSE_KEY_OUTSIDE_THE_LANE_BLOCK,
            "first key 0x%X is outside this lane's block" % first_key)
    if len(roll.items) > MAX_DROPS_PER_KILL:
        raise MobLootContractError(
            REFUSE_TOO_MANY_DROPS_FOR_ONE_KILL,
            "%d objects for one kill exceeds the lane ceiling of %d"
            % (len(roll.items), MAX_DROPS_PER_KILL))
    if position is None:
        base = (mob.x, mob.y, mob.z)
    else:
        try:
            base = tuple(position)
        except TypeError:
            raise MobLootContractError(
                REFUSE_POSITION_NOT_FINITE,
                "position must be an (x, y, z) triple") from None
        if len(base) != 3:
            raise MobLootContractError(
                REFUSE_POSITION_NOT_FINITE,
                "position must be an (x, y, z) triple")
    x0 = _require_float32(base[0], "position x")
    y0 = as_wire_float(_require_float32(base[1], "position y"))
    z0 = as_wire_float(_require_float32(base[2], "position z"))
    drops = []
    for offset, item in enumerate(roll.items):
        key = first_key + offset
        if key >= DROP_KEY_LIMIT:
            raise MobLootContractError(
                REFUSE_KEY_OUTSIDE_THE_LANE_BLOCK,
                "this kill would run past the end of the lane's key block")
        x = as_wire_float(x0 + DROP_SCATTER_STEP * offset)
        if not math.isfinite(x):
            raise MobLootContractError(
                REFUSE_POSITION_NOT_FINITE,
                "the scattered position does not survive the f32 round trip")
        drops.append(GroundDrop(
            key, item.item_id, item.quantity, x, y0, z0,
            actor_identity, killer_identity,
        ))
    return tuple(drops)


def commit_drops(ledger_now: DropLedger, drops: Any) -> DropLedger:
    """Compare-and-swap a kill's drops into the ledger.

    Returns the NEXT ledger.  Refuses -- rather than silently merging -- when
    a key it is asked to add is already on the ground, because the only way
    that happens is that the caller built its drops against a ledger that has
    since moved, and merging would put two different items under one key the
    client is meant to be able to tell apart.
    """
    if type(ledger_now) is not DropLedger:
        raise MobLootContractError(
            REFUSE_TYPE_NOT_TYPED_RECORD, "ledger must be a typed DropLedger")
    incoming = tuple(drops)
    for drop in incoming:
        if type(drop) is not GroundDrop:
            raise MobLootContractError(
                REFUSE_TYPE_NOT_TYPED_RECORD,
                "every drop must be a typed GroundDrop")
    existing = {drop.drop_key for drop in ledger_now.drops}
    for drop in incoming:
        if drop.drop_key in existing:
            raise MobLootContractError(
                REFUSE_LEDGER_STALE,
                "drop key 0x%X is already on the ground; rebuild the drops "
                "against the current ledger and commit again -- do NOT "
                "re-roll, that would give one kill two rolls" % drop.drop_key)
    merged = tuple(sorted(
        ledger_now.drops + incoming, key=lambda row: row.drop_key))
    return DropLedger(merged, ledger_now.generation + 1)


def take_drop(ledger_now: DropLedger, drop_key: int) -> tuple:
    """Remove one drop from the ledger and return ``(next_ledger, drop)``.

    This is the seam the pickup half will use, and it is deliberately the only
    thing this module offers toward it: it removes a row from a value.  It
    sends nothing, replies to nothing and writes nothing -- see NONCLAIM 4.
    """
    if type(ledger_now) is not DropLedger:
        raise MobLootContractError(
            REFUSE_TYPE_NOT_TYPED_RECORD, "ledger must be a typed DropLedger")
    _require_int(drop_key, "drop key", 0, 0xFFFFFFFF)
    taken = ledger_now.get(drop_key)
    remaining = tuple(
        drop for drop in ledger_now.drops if drop.drop_key != drop_key)
    return DropLedger(remaining, ledger_now.generation + 1), taken


# ---------------------------------------------------------------------------
# The composer.  Two independent derivations of the same element, compared on
# every call: if the legacy tag helpers ever drift, this lane stops emitting
# rather than emitting something a client has never accepted.
# ---------------------------------------------------------------------------
def _element_via_tags(legacy: Any, drop: GroundDrop) -> bytes:
    return (
        legacy.u32tag(ELEMENT_KEY_TAG, drop.drop_key)
        + legacy.u8tag(ELEMENT_MASK_TAG, ELEMENT_MASK_POSITION_AND_DWORD)
        + legacy.u32tag(ELEMENT_PAYLOAD_TAG, drop.item_id)
        + legacy.f32tag(drop.x)
        + legacy.f32tag(drop.y)
        + legacy.f32tag(drop.z)
    )


def _element_via_struct(drop: GroundDrop) -> bytes:
    """The same element built from the pinned layout, with no legacy helper."""
    return (
        bytes([ELEMENT_KEY_TAG]) + struct.pack("<I", drop.drop_key)
        + bytes([ELEMENT_MASK_TAG, ELEMENT_MASK_POSITION_AND_DWORD])
        + bytes([ELEMENT_PAYLOAD_TAG]) + struct.pack("<I", drop.item_id)
        + bytes([ELEMENT_F32_TAG]) + struct.pack("<f", drop.x)
        + bytes([ELEMENT_F32_TAG]) + struct.pack("<f", drop.y)
        + bytes([ELEMENT_F32_TAG]) + struct.pack("<f", drop.z)
    )


def drop_element(legacy: Any, drop: Any) -> bytes:
    """One 0x5F85B0 element for one ground drop, mask 0x12."""
    if type(drop) is not GroundDrop:
        raise MobLootContractError(
            REFUSE_TYPE_NOT_TYPED_RECORD, "drop must be a typed GroundDrop")
    via_tags = _element_via_tags(legacy, drop)
    via_struct = _element_via_struct(drop)
    if via_tags != via_struct:
        raise MobLootContractError(
            REFUSE_ELEMENT_ENCODER_DISAGREES,
            "the legacy tag helpers and the pinned layout disagree; this lane "
            "refuses to emit a shape no client has accepted")
    return via_tags


def drop_pc(legacy: Any, drop: Any) -> bytes:
    """The single-element RuntimeRes pc that carries one ground drop."""
    element = drop_element(legacy, drop)
    pc = bytearray()
    pc += legacy.u16tag(0x12, legacy.GSCN_RUNTIME_PROTOCOL_RES)
    pc += legacy.u32tag(0x14, 0)
    pc += legacy.u8tag(0x08, ENVELOPE_VERSION)
    pc += legacy.u8tag(0x0B, 0)                                # inherited none
    pc += legacy.u8tag(0x0B, RUNTIME_DERIVED_BIT_GROUND_LIST)  # derived 0x08
    pc += legacy.u16tag(ELEMENT_LIST_COUNT_TAG, 1)             # ONE element
    pc += element
    pc = bytes(pc)
    if len(pc) != DROP_PC_SIZE:
        raise MobLootContractError(
            REFUSE_COMPOSED_BYTES_OFF_PIN,
            "a one-element ground pc is %d bytes, composed %d"
            % (DROP_PC_SIZE, len(pc)))
    coordinates = b"".join(pc[start:end] for start, end in DROP_COORD_SPANS)
    if coordinates != struct.pack("<fff", drop.x, drop.y, drop.z):
        raise MobLootContractError(
            REFUSE_COMPOSED_BYTES_OFF_PIN,
            "the composed coordinates are not the drop's coordinates")
    return pc


def drop_frames(legacy: Any, drops: Any) -> tuple:
    """One framed single-element message per drop, in ledger order.

    ONE element per frame on purpose: a combined multi-record derived-mask
    collection is the one shape a real client has already rejected with
    ErrorData=28317 (the V43 lesson the probe lane also obeys).
    """
    out = []
    for drop in drops:
        pc = drop_pc(legacy, drop)
        frame = legacy.frame_pc(pc)
        if len(frame) != DROP_FRAME_SIZE:
            raise MobLootContractError(
                REFUSE_COMPOSED_BYTES_OFF_PIN,
                "a framed one-element ground message is %d bytes, composed %d"
                % (DROP_FRAME_SIZE, len(frame)))
        shifted = b"".join(
            frame[start + DROP_FRAME_COORD_SHIFT:end + DROP_FRAME_COORD_SHIFT]
            for start, end in DROP_COORD_SPANS
        )
        if shifted != struct.pack("<fff", drop.x, drop.y, drop.z):
            raise MobLootContractError(
                REFUSE_COMPOSED_BYTES_OFF_PIN,
                "the framed coordinates are not the drop's coordinates")
        out.append((pc, frame))
    return tuple(out)


def refresh_frames(legacy: Any, ledger: Any) -> tuple:
    """Re-emit every live drop.  AN EXPERIMENT, NOT A BEHAVIOUR.

    The measured lifetime of a ground object is 0.633 s and the attended run
    found nothing standing afterwards, so "it stays" is not something this
    lane can deliver by composing bytes.  Re-emission is the only lever it
    has, and whether it holds the object, restarts its effect or does nothing
    at all is UNMEASURED (NONCLAIM 12).  ``DROP_REFRESH_MS`` is our guess at a
    cadence and is not a measurement either.
    """
    if type(ledger) is not DropLedger:
        raise MobLootContractError(
            REFUSE_TYPE_NOT_TYPED_RECORD, "ledger must be a typed DropLedger")
    return drop_frames(legacy, ledger.drops)


def money_element(legacy: Any, money: Any) -> bytes:
    """Refuse, by name.  A money slot has no item id and the element needs one."""
    raise MobLootContractError(
        REFUSE_MONEY_HAS_NO_ELEMENT,
        "money cannot be placed on the ground through this pipe: the element "
        "carries an item id and nothing else")


# ---------------------------------------------------------------------------
# The pin document and the report.
# ---------------------------------------------------------------------------
PIN_ID = "port_royal_field_mob_loot_001"
PIN_BUILD_ORDER = MOB_LOOT_BUILD_ORDER
PIN_LANE = MOB_LOOT_LANE


def pin_document(legacy: Any) -> dict:
    """What this lane emits, computed rather than typed, for scenarios/."""
    sample = GroundDrop(
        DROP_KEY_BASE, 2400046, 1, as_wire_float(1.0), as_wire_float(2.0),
        as_wire_float(3.0), 0x201F, 0x0101,
    )
    pc = drop_pc(legacy, sample)
    frame = legacy.frame_pc(pc)
    masked = bytearray(pc)
    for start, end in DROP_COORD_SPANS:
        masked[start:end] = b"\x00" * (end - start)
    return {
        "schema": 1,
        "id": PIN_ID,
        "build_order": PIN_BUILD_ORDER,
        "lane": PIN_LANE,
        "milestone": MOB_LOOT_MILESTONE,
        "test_only": False,
        "production_allowed": True,
        "scenario": None,
        "wire": {
            "runtime_derived_bit": RUNTIME_DERIVED_BIT_GROUND_LIST,
            "element_mask": ELEMENT_MASK_POSITION_AND_DWORD,
            "element_field_order": list(ELEMENT_FIELD_ORDER),
            "elements_per_frame": 1,
            "pc_size": DROP_PC_SIZE,
            "frame_size": DROP_FRAME_SIZE,
            "masked_pc_sha256": hashlib.sha256(bytes(masked)).hexdigest().upper(),
            "sample_frame_size": len(frame),
        },
        "lane_constants": {
            "drop_key_base": DROP_KEY_BASE,
            "drop_key_limit": DROP_KEY_LIMIT,
            "scatter_step": DROP_SCATTER_STEP,
            "refresh_ms": DROP_REFRESH_MS,
            "max_drops_per_kill": MAX_DROPS_PER_KILL,
        },
        "measured": {
            "ground_drop_persists": not GROUND_DROP_DOES_NOT_PERSIST,
            "observed_lifetime_seconds": GROUND_DROP_OBSERVED_LIFETIME_SECONDS,
            "observed_ids_on_the_wire": [2200423, 2600001],
        },
        "tables": {
            "scene": field_drop_tables.SCENE,
            "normal_sets": sorted(field_drop_tables.DROPS_NORMAL),
            "equipment_sets": sorted(field_drop_tables.DROPS_EQUIPMENT),
            "specially_sets": sorted(field_drop_tables.DROPS_SPECIALLY),
            "item_ids": len(field_drop_tables.ITEMS),
            "source_digests": dict(field_drop_tables.SOURCE_DIGESTS),
        },
        "refusals": list(MOB_LOOT_REFUSAL_REASONS),
        "nonclaims": list(MOB_LOOT_NONCLAIMS),
        "wiring": MOB_LOOT_WIRING,
    }


def loot_report(mob: Any, roll: DropRoll) -> dict:
    """A human-readable summary of one roll, for a console and a round note."""
    mob = _require_mob(mob)
    if type(roll) is not DropRoll:
        raise MobLootContractError(
            REFUSE_TYPE_NOT_TYPED_RECORD, "roll must be a typed DropRoll")
    return {
        "mob": mob.display_name,
        "template_id": mob.template_id,
        "identity": mob.actor_identity,
        "items": [
            {
                "item_id": item.item_id,
                "name": item.display_name,
                "quantity": item.quantity,
                "source": item.source_table,
                "set_id": item.source_set_id,
                "drop_model_type": item.drop_model_type,
            }
            for item in roll.items
        ],
        "money": [
            {"amount": row.amount, "source": row.source_table, "tag": row.tag}
            for row in roll.money
        ],
        "draws": roll.draws,
        "refusals": [list(row) for row in roll.refusals],
        "placeable": roll.placeable_count,
    }
