"""Domain-facing persistence contract; SQLiteStore is the first implementation."""
from typing import Protocol
from .model import Character, Position
from .inventory import BackpackState

class CharacterRepository(Protocol):
    def migrate(self) -> None: ...
    def expire_open_sessions(self) -> None: ...
    def ensure_account(self, name: str) -> int: ...
    def open_session(self, account_id: int) -> str: ...
    def close_session(self, session_id: str) -> None: ...
    def create_character(self, account_id: int, name: str, name_key: str,
                         fingerprint: str, build_wire, position: Position) -> Character: ...
    def list_characters(self, account_id: int) -> list[Character]: ...
    def get_character(self, character_id: int) -> Character: ...
    def select_character(self, session_id: str, selector: int) -> Character: ...
    def save_position(self, session_id: str, character_id: int,
                      position: Position) -> None: ...
    def get_backpack(self, session_id: str, character_id: int) -> BackpackState: ...
    def apply_v111_stack_merge(self, session_id: str,
                               character_id: int) -> BackpackState | None: ...
    # PF-HYPOTHESIS-LEDGER: HYP-PF-008 active
    def apply_hypothesized_v111_slot2_move(
        self, session_id: str, character_id: int,
    ) -> BackpackState | None: ...
    # PF-HYPOTHESIS-LEDGER: HYP-PF-010 active
    def move_backpack_item_to_free_slot(
        self, session_id: str, character_id: int,
        item_identity: int, destination_slot: int,
    ) -> BackpackState | None: ...
