"""Domain-facing persistence contract; SQLiteStore is the first implementation."""
from typing import Protocol
from .model import Character, Position

class CharacterRepository(Protocol):
    def ensure_account(self, name: str) -> int: ...
    def open_session(self, account_id: int) -> str: ...
    def close_session(self, session_id: str) -> None: ...
    def list_characters(self, account_id: int) -> list[Character]: ...
    def select_character(self, session_id: str, selector: int) -> Character: ...
    def save_position(self, character_id: int, position: Position) -> None: ...
