"""Bg0004 (Slave Market Island) placement roster - LANE-A door-priority build.

COO-DECISION 2026-08-30T14:41 (`pf_bridge/notes_to_chief/20260830_1441_COO-
DECISION-scene4-slave-market-first-door.md`) approved LANE-A's own
recommendation (round `12lyda`, `20260830_1434_LANE-A-STATUS-r236-gate-
verified-narrow-plus-door-priority-recommendation.md`) to build the same
CLINE->MOBS crosswalk BUILD-001 (bg0001) used, applied to scene 4: highest
native placement count (116) of the ten still-shut doors that lane's own
`R236` gate-scope check found equally safe, and already referenced as
`world_m2_sea_destination`'s second Q_TELEPORT1 destination.

RE-128 (2026-08-28, RE runner, closed, cross-checked by this lane) is the
mechanism this module reuses, unchanged: a scene file names a Mob-Set number,
not a `MOBS.n_ID` directly - the real identity comes from

    SCENE_NAME[s_MODLE_ID=BG0004].n_CLINE_TYPE = 4
    CLINE[(n_CLINE_TYPE=4, n_CREATURE_TYPE=<Mob-Set number>)].n_LEADER_BK1
        = the real MOBS.n_ID
    MOBS[n_ID].s_OUTFIT      = the avatar template the client loads
    MOBS_TIP[n_ID].s_NAME    = the name the client draws under the actor

`bg0004.placements.tsv` names its rows `Mob_Set_NN MM`, the SAME convention
`field_mob_tables.py` mines for bg0001 (not bg0002's `MOBSET_NN MM`), so this
scene is the CLINE-crosswalk kind, matching what the COO letter asked for
literally ("crosswalk CLINE->MOBS แบบเดียวกับ BUILD-001"), not the simpler
direct-lookup join `scene2_prison_exile_tables.py` used.

NOT MACHINE-GENERATED THIS ROUND, SAME REASON AS SCENE 2's TABLE.
`tools/pf_mine_scene_mob_roster.py` is LANE-B's generator and lives outside
this lane's write zone this round; also, that tool's own selection rule
(unambiguous outfit + rank!=0 + ai_combat!=0) is a HOSTILE-roster filter, not
the full-identity census BUILD-001's own module builds for bg0001 - reusing
it here would silently narrow this scene to monsters only, dropping every
named townsperson (Columbus, Angelina, the slave traders) BUILD-001's own
precedent says to keep. So this join was run as a script against the exact
same committed tables that tool reads (recorded below, reproducible), not
hand-typed and not machine-generated by a tool this lane does not own.

SOURCES (pf_bridge clone, sha256 at read time, 2026-09-01)
    placements    gamedata/scene/bg0004/bg0004.placements.tsv
                  43ae4a104b760059bba4e7c170bcc7db5af0fcd2b58f50bf1b3613be182e63f5
    cline         gamedata/tables/CONSTDATA_TH__CLINE.tsv
                  aa4a55b8db882eb965d0b7e186cd7bc7b5a81da8f057fee24586a27c94b2dc40
    mobs          gamedata/tables/CONSTDATA_TH__MOBS.tsv
                  3c0d33d68f832eefda56c845495008338dcef56f4277584b9ca479b7e1b3916b
    mobs_tip      gamedata/tables/TEXTDATA_TH__MOBS_TIP.tsv
                  e25ac667c9029e07752fbfd5d13b548d2e62ea439936884f30187c0c553ce38f
    standard_mob  gamedata/tables/CONSTDATA_TH__STANDARD_MOB.tsv
                  4b2db7f9553c877c2ec471105754dd08982d9e80027cc468c1ceaee840d68925
    scene_name    gamedata/tables/CONSTDATA_TH__SCENE_NAME.tsv
                  e38114a802576266ce37b2abcf8ebce3f105d7d5abaf4bc5ca066e7848c5d60b
(cline/mobs/mobs_tip/standard_mob/scene_name digests are the SAME five values
`world_port_royal_identity.py` and `field_mob_tables.py` already pin for
bg0001 and `scene2_prison_exile_tables.py` pins three of for bg0002 - checked
again here rather than assumed, same discipline those modules use.)

THE JOIN, EXACTLY, SO IT CAN BE RE-RUN
1. Read every row of the placements TSV (116 rows).  Its `template_ids`
   column is the scene's own Mob-Set number - checked against the name
   column's own `Mob_Set_<NN> <MM>` text for all 116 rows; TWO disagree
   (index 82 says "Mob_Set_34 08" but `template_ids`=45, index 83 says
   "Mob_Set_34 09" but `template_ids`=46).  `template_ids` is the field this
   project's own precedent (the mining tool's docstring, and RE-128's own
   crosswalk) treats as authoritative - the name column is cosmetic - so
   both rows resolve via `template_ids` (45, 46), NOT the number their own
   name text shows.  Recorded here rather than silently picked, exactly the
   discrepancy-naming discipline `scene2_prison_exile_tables.py`'s own
   "COUNT DISCREPANCY" section models.
2. Mob-Set number is looked up in `CLINE[(n_CLINE_TYPE=4, n_CREATURE_TYPE=
   <Mob-Set number>)].n_LEADER_BK1` -> the real `MOBS.n_ID`.  One Mob-Set
   number in this scene (1, placement index 0) has NO row in this key at
   all in CLINE - UNRESOLVED, not placed, not guessed.
3. For every remaining row, `visual_preset` is `MOBS.s_OUTFIT` (44 of the 85
   CLINE-resolved rows have a `;`-separated outfit list; this module ships
   the FIRST listed variant and records `ambiguous_outfit = True`, the SAME
   default `world_port_royal_identity.py`'s `MULTI_VARIANT_OUTFITS` and
   `scene2_prison_exile_tables.py`'s "AMBIGUOUS OUTFIT" section both use -
   not independently re-decided here).  `display_name`/`title` are
   `MOBS_TIP.s_NAME`/`s_TITLE`, and `max_hp` is
   `STANDARD_MOB[MOBS.n_LEVEL_MIN].n_HPMAX` - the exact derivation BUILD-001
   and M1-P both already use.
4. SEVEN Mob-Set numbers (101-107, 32 placements total) resolve in CLINE and
   in MOBS but have NO `MOBS_TIP` row, so `display_name` is empty.  Following
   `scene2_prison_exile_tables.py`'s convention (not bg0001's, which ships an
   empty-named row), THIS module refuses an empty display name into
   UNRESOLVED rather than shipping a nameless actor - see `load_known_
   placements`.  Two different reasons hide inside those 32:
     - Mob-Set 101-106 (6 placements, MOBS n_ID 10014-10019): MOBS.s_NAME
       (internal, not MOBS_TIP, and not shipped as a display name by this or
       any sibling module) reads (Chinese, machine-translated by this round
       for triage only, not shipped anywhere) "mechanism_<terrain feature>_
       pathfinding-aid" - these read as invisible scenery/pathfinding
       helpers, not NPCs, which is consistent with them having no player-
       facing name.
     - Mob-Set 107 (25 placements, MOBS n_ID 917): the SAME n_ID
       `world_port_royal_identity.py`'s own docstring already names as
       having a MOBS row but no MOBS_TIP row in BG0001 too (Mob-Set 98 and
       103 there).  MOBS.s_NAME for 917 is "(Chinese) Training Iron Man
       (invisible mechanism monster)" - directly relevant to the still-open
       `RE-155` ticket ("NPC name color ... Training Iron Man red"), noted
       here as a cross-reference for whoever next reads RE-155, NOT
       something this module fixes (naming it is this lane's whole job here
       - deciding what a nameless actor should be called is not).
5. 84 of 116 placements resolve to a named, bodied actor.  84 KNOWN + 32
   UNRESOLVED = 116, matches the source file exactly.

NO OWNER-CONFIRMED ANCHOR EXISTS YET FOR THIS SCENE.  Unlike bg0001 (`GT-078`
video, `RE-128`'s two placement anchors) and bg0002 (photographed Sebastian/
Pike, the Veronica HUD reading), nobody has stood in Slave Market Island and
confirmed a single one of these 84 identities by eye.  The RE-128 mechanism
itself is trusted project-wide (bg0001 + bg0002 both independently confirm
it); applying an already-trusted mechanism to a new scene is exactly what
CHARTER-02's "build around the hole, do not stop" rule asks for - but this
module's own roster is UNVERIFIED beyond that mechanism until a human looks.
`census_console_line`/`actor_lines` exist so a queue ticket has real console
output to check against before anyone is asked to look at a screen, matching
the headless-proof-before-owner-look discipline `PANYA-DECISION 2026-08-27
20:10` set for bg0002 and this lane still follows.

WHY THE NAMES SHOULD BE READ AS PLAUSIBLE, NOT AS PROOF.  The resolved cast
is thematically coherent with "Slave Market Island" without this module
having invented anything: Columbus (index 1, matching bg0001/bg0002's
Columbus reuse pattern), "Wealthy slave buyer", "Lecherous slave buyer",
"Angelina / Princess Slave", "Beirut / Passionate Slave", "Gladiator Slave
Girl", an arena cluster (Crazy Rose Regina, Blood dragon Norman), and a
"Slave Market Bulletin Board" - every one of those strings came out of
`MOBS_TIP.s_NAME`/`s_TITLE` for a `MOBS.n_ID` this scene's own CLINE block
names, not composed by this module.  Coherence is evidence FOR the mechanism
being right here too, but it is a pattern-match this lane made, not a client
observation - do not upgrade it past that in a future round's status letter.
"""

from __future__ import annotations

from dataclasses import dataclass
import math
from typing import Any

_FLOAT32_MAX = 3.4028234663852886e38


SCENE = "Bg0004"
SCENE_N_ID = 4
SCENE_CLINE_TYPE = 4
NAMING_SCHEME = "Mob_Set_NN_MM_joined_through_CLINE_type4_leader_bk1_to_MOBS_n_ID"

SOURCE_DIGESTS = {
    "placements": (
        "43ae4a104b760059bba4e7c170bcc7db5af0fcd2b58f50bf1b3613be182e63f5"
    ),
    "cline": "aa4a55b8db882eb965d0b7e186cd7bc7b5a81da8f057fee24586a27c94b2dc40",
    "mobs": "3c0d33d68f832eefda56c845495008338dcef56f4277584b9ca479b7e1b3916b",
    "mobs_tip": "e25ac667c9029e07752fbfd5d13b548d2e62ea439936884f30187c0c553ce38f",
    "standard_mob": (
        "4b2db7f9553c877c2ec471105754dd08982d9e80027cc468c1ceaee840d68925"
    ),
    "scene_name": (
        "e38114a802576266ce37b2abcf8ebce3f105d7d5abaf4bc5ca066e7848c5d60b"
    ),
}

TOTAL_PLACEMENT_COUNT = 116
KNOWN_COUNT = 84
UNRESOLVED_COUNT = 32

# The two rows whose own name text disagrees with their (authoritative)
# template_ids column - see docstring step 1.  Recorded as data, not just
# prose, so a test can hold the module to naming both.
NAME_TEMPLATE_ID_MISMATCHES = (
    (82, "Mob_Set_34 08", 45),
    (83, "Mob_Set_34 09", 46),
)

# (placement_index, mm_instance, n_id, x, y, z, visual_preset, ambiguous_outfit,
#  display_name, title, level, level_max, rank, ai_wander, ai_combat,
#  speed_walk, max_hp, drops_normal, drops_equipment, drops_specially)
KNOWN_PLACEMENTS = [
    (1, 1, 67, -17773.109375, 19926.1328125, 1481.3291015625, 'M055_000_000_N', False, 'Columbus', 'Marine Transport Station', 50, 50, 0, 2, 0, 150, 23976, 0, 0, 0),
    (2, 1, 68, -4948.75341796875, 16126.60546875, 1598.4730224609375, 'P_FEMALE_012_000_VENONIKA', False, 'Veronica', 'Apprentice Witch', 50, 50, 0, 1, 0, 100, 23976, 0, 0, 0),
    (3, 1, 69, -12179.4208984375, 23516.158203125, 1534.238525390625, 'M015_000_001_SP3', False, 'Mori Hiroko', 'Vagabond Messenger', 50, 50, 0, 2, 0, 150, 23976, 0, 0, 0),
    (4, 1, 70, -4239.1455078125, 14551.4169921875, 1716.2342529296875, 'M070_000_000_N', False, 'Wealthy slave buyer', '', 50, 50, 0, 1, 0, 100, 23976, 0, 0, 0),
    (5, 1, 71, -1640.8388671875, 15165.046875, 1679.5806884765625, 'M001_001_000_SP2', False, 'Lecherous slave buyer', '', 50, 50, 0, 1, 0, 150, 23976, 0, 0, 0),
    (6, 1, 72, -7192.53076171875, 18728.080078125, 1677.0467529296875, 'M068_000_001_SP3', False, 'Battle Arena gambler', '', 50, 50, 0, 1, 0, 150, 23976, 0, 0, 0),
    (7, 1, 73, -1946.5809326171875, 16912.08984375, 1558.7724609375, 'M051_000_001_N', False, 'Angelina', 'Princess Slave', 50, 50, 0, 2, 0, 150, 23976, 0, 0, 0),
    (8, 1, 74, -4090.9609375, 18370.048828125, 1591.0484619140625, 'M073_000_000_N', False, 'Aston', 'Slave Traders ', 50, 50, 0, 2, 0, 150, 23976, 0, 0, 0),
    (9, 1, 75, -5326.4091796875, 23845.40234375, 2367.775634765625, 'P_MALE_003_002_LARGIN', False, 'AstonLarkin', 'Fighter Club Chairman', 50, 50, 0, 2, 0, 150, 23976, 0, 0, 0),
    (10, 1, 76, -908.0391235351562, 13699.5, 1599.3037109375, 'M023_000_001_SP1', False, 'Hasan', 'Vendor', 50, 50, 0, 2, 0, 150, 23976, 0, 0, 0),
    (11, 1, 77, -2630.90625, 17509.8125, 1612.31591796875, 'P_MALE_015_000_LING', False, 'Ringer', 'Escaped Slave', 50, 50, 0, 2, 0, 150, 23976, 0, 0, 0),
    (12, 1, 78, -4241.1484375, 13922.19921875, 1621.0089111328125, 'P_MALE_015_000_BERULT', False, 'Beirut', 'Passionate Slave', 50, 50, 0, 2, 0, 150, 23976, 0, 0, 0),
    (13, 1, 79, -10203.685546875, 19839.98828125, 1621.8746337890625, 'P_FEMALE_015_000_MAYA', False, 'Maya', 'Beautiful Slave', 50, 50, 0, 2, 0, 150, 23976, 0, 0, 0),
    (14, 1, 80, 16126.4306640625, 18300.78515625, 3851.40185546875, 'P_MALE_015_000_ZERALTIN', False, 'Salahuddin', 'Prince Slaves', 50, 50, 0, 2, 0, 150, 23976, 0, 0, 0),
    (15, 1, 81, -371.5741882324219, 16448.9765625, 1735.8133544921875, 'P_MALE_015_000_SLAVE', False, 'Unwanted slaves', '', 50, 50, 0, 2, 0, 150, 23976, 0, 0, 0),
    (16, 1, 82, 22007.466796875, 20767.078125, 4079.979248046875, 'P_MALE_003_000_DANKEN', False, 'Duncan', 'Wounded Fighter', 50, 50, 0, 2, 0, 150, 23976, 0, 0, 0),
    (17, 1, 83, 20705.20703125, 18382.251953125, 3799.4501953125, 'P_MALE_003_002_CLOUZE', False, 'Kelas', 'Trainer', 50, 50, 0, 2, 0, 150, 23976, 0, 0, 0),
    (18, 1, 84, 18533.6640625, 7422.06640625, 4078.504638671875, 'M019_002_000_SP1', False, 'Qina', 'Fighter Apprentice ', 50, 50, 0, 1, 0, 150, 23976, 0, 0, 0),
    (19, 1, 85, 17872.638671875, -4114.8486328125, 4026.408203125, 'P_MALE_003_000_KAIM', False, 'Kaim', 'Novice Fighter ', 50, 50, 0, 1, 0, 150, 23976, 0, 0, 0),
    (20, 1, 86, 18225.17578125, -2757.53759765625, 4068.76708984375, 'M015_000_001_SP1', False, 'Mori Hiroko', 'Vagabond Messenger', 50, 50, 0, 2, 0, 150, 23976, 0, 0, 0),
    (21, 1, 87, -10591.2998046875, -10071.662109375, 2828.8818359375, 'M076_000_000_N', False, 'Sea Phantom', 'Dark Captain', 50, 50, 0, 2, 0, 150, 23976, 0, 0, 0),
    (22, 1, 88, -3964.556884765625, -13227.8212890625, 2008.0692138671875, 'P_FEMALE_030_000_KAREN', False, 'Karen', 'Female Fighter', 50, 50, 0, 2, 0, 150, 23976, 0, 0, 0),
    (23, 1, 89, 4786.4697265625, -19408.611328125, 1918.884765625, 'P_FEMALE_015_000_PETIRA', False, 'Betula', 'Panic Slave', 50, 50, 0, 2, 0, 150, 23976, 0, 0, 0),
    (24, 1, 90, 1722.82275390625, -19046.650390625, 1971.3095703125, 'M073_000_001_N', False, 'Hood', 'Shameless Slave Traders ', 50, 50, 0, 2, 0, 150, 23976, 0, 0, 0),
    (25, 1, 91, -8808.7373046875, -1143.334228515625, 2362.6962890625, 'M074_000_001_N', False, 'Local people', '', 50, 50, 0, 1, 0, 150, 23976, 0, 0, 0),
    (26, 1, 92, 9110.6494140625, -8708.98828125, 2601.748046875, 'P_FEMALE_015_000_PENNY', False, 'Penny', 'Cute Girl Slave', 50, 50, 0, 1, 0, 150, 23976, 0, 0, 0),
    (27, 1, 93, 3738.38720703125, 18302.33984375, 1803.738037109375, 'M028_000_000_SP1', True, 'Scythe Beetle', '', 46, 48, 1, 16, 380, 100, 18424, 2701003, 5400002, 2802266),
    (28, 2, 93, 6442.29345703125, 21859.40625, 2047.102783203125, 'M028_000_000_SP1', True, 'Scythe Beetle', '', 46, 48, 1, 16, 380, 100, 18424, 2701003, 5400002, 2802266),
    (29, 3, 93, 12171.1875, 25974.19921875, 2912.14208984375, 'M028_000_000_SP1', True, 'Scythe Beetle', '', 46, 48, 1, 16, 380, 100, 18424, 2701003, 5400002, 2802266),
    (30, 1, 94, 18620.16015625, 25247.43359375, 3382.362548828125, 'M020_001_000_SP1', False, 'An Gebo Little Firebird', '', 47, 49, 1, 16, 300, 100, 19710, 2701003, 5400002, 2802253),
    (31, 2, 94, 21511.134765625, 22272.46484375, 3924.55224609375, 'M020_001_000_SP1', False, 'An Gebo Little Firebird', '', 47, 49, 1, 16, 300, 100, 19710, 2701003, 5400002, 2802253),
    (32, 3, 94, 22519.201171875, 18964.6953125, 4041.401611328125, 'M020_001_000_SP1', False, 'An Gebo Little Firebird', '', 47, 49, 1, 16, 300, 100, 19710, 2701003, 5400002, 2802253),
    (33, 1, 95, 21389.650390625, 16740.4453125, 3883.948486328125, 'M017_000_001_SP1', True, 'Dragon Gladiator', '', 48, 50, 1, 16, 270, 100, 21045, 2701003, 5400002, 0),
    (34, 2, 95, 16122.193359375, 17238.908203125, 3753.192626953125, 'M017_000_001_SP1', True, 'Dragon Gladiator', '', 48, 50, 1, 16, 270, 100, 21045, 2701003, 5400002, 0),
    (35, 3, 95, 13761.8359375, 14000.6298828125, 3750.57470703125, 'M017_000_001_SP1', True, 'Dragon Gladiator', '', 48, 50, 1, 16, 270, 100, 21045, 2701003, 5400002, 0),
    (36, 4, 95, 16096.0185546875, 9812.8603515625, 3724.12255859375, 'M017_000_001_SP1', True, 'Dragon Gladiator', '', 48, 50, 1, 16, 270, 100, 21045, 2701003, 5400002, 0),
    (37, 5, 95, 20651.849609375, 5983.28076171875, 4134.2294921875, 'M017_000_001_SP1', True, 'Dragon Gladiator', '', 48, 50, 1, 16, 270, 100, 21045, 2701003, 5400002, 0),
    (38, 1, 96, 24056.185546875, 16266.4833984375, 4119.9599609375, 'M011_000_002_SP1', True, 'Forest Green Eagle', '', 50, 52, 1, 10, 210, 100, 23976, 2701003, 5400003, 2802236),
    (39, 2, 96, 24489.69140625, 12121.2080078125, 4617.359375, 'M011_000_002_SP1', True, 'Forest Green Eagle', '', 50, 52, 1, 10, 210, 100, 23976, 2701003, 5400003, 2802236),
    (40, 3, 96, 22932.392578125, 2867.386962890625, 4269.3525390625, 'M011_000_002_SP1', True, 'Forest Green Eagle', '', 50, 52, 1, 10, 210, 100, 23976, 2701003, 5400003, 2802236),
    (41, 4, 96, 22723.349609375, 1776.897216796875, 4294.341796875, 'M011_000_002_SP1', True, 'Forest Green Eagle', '', 50, 52, 1, 10, 210, 100, 23976, 2701003, 5400003, 2802236),
    (42, 1, 97, 22691.337890625, 14229.287109375, 4422.484375, 'M011_000_002_SP3', False, 'Mutant Green Eagle', '', 51, 53, 1, 16, 214, 100, 25564, 2701003, 5400003, 2802236),
    (43, 6, 95, 21440.833984375, -2466.861328125, 4285.99853515625, 'M017_000_001_SP1', True, 'Dragon Gladiator', '', 48, 50, 1, 16, 270, 100, 21045, 2701003, 5400002, 0),
    (44, 7, 95, 17117.8984375, -3186.320556640625, 3750.588134765625, 'M017_000_001_SP1', True, 'Dragon Gladiator', '', 48, 50, 1, 16, 270, 100, 21045, 2701003, 5400002, 0),
    (45, 8, 95, 13552.7138671875, -836.998779296875, 2953.02490234375, 'M017_000_001_SP1', True, 'Dragon Gladiator', '', 48, 50, 1, 16, 270, 100, 21045, 2701003, 5400002, 0),
    (46, 9, 95, 9901.57421875, -1174.7373046875, 2611.3154296875, 'M017_000_001_SP1', True, 'Dragon Gladiator', '', 48, 50, 1, 16, 270, 100, 21045, 2701003, 5400002, 0),
    (47, 1, 101, 8150.90478515625, -16054.306640625, 1913.0, 'M006_001_001_SP1', True, 'Swamp Tortoise', '', 56, 58, 1, 16, 164, 100, 34530, 2701003, 5400003, 2802232),
    (48, 2, 101, 10952.009765625, -12999.9619140625, 1785.599609375, 'M006_001_001_SP1', True, 'Swamp Tortoise', '', 56, 58, 1, 16, 164, 100, 34530, 2701003, 5400003, 2802232),
    (49, 3, 101, 13524.8447265625, -15144.7587890625, 1978.5423583984375, 'M006_001_001_SP1', True, 'Swamp Tortoise', '', 56, 58, 1, 16, 164, 100, 34530, 2701003, 5400003, 2802232),
    (50, 4, 101, 5236.3349609375, -12683.4140625, 1911.72802734375, 'M006_001_001_SP1', True, 'Swamp Tortoise', '', 56, 58, 1, 16, 164, 100, 34530, 2701003, 5400003, 2802232),
    (51, 5, 101, -657.7073974609375, -12683.4140625, 1953.4510498046875, 'M006_001_001_SP1', True, 'Swamp Tortoise', '', 56, 58, 1, 16, 164, 100, 34530, 2701003, 5400003, 2802232),
    (52, 6, 101, -5071.7080078125, -12683.4140625, 1981.3673095703125, 'M006_001_001_SP1', True, 'Swamp Tortoise', '', 56, 58, 1, 16, 164, 100, 34530, 2701003, 5400003, 2802232),
    (53, 1, 99, 3144.10302734375, -6236.673828125, 1818.9404296875, 'M008_000_001_SP1', True, 'Moor Slime', '', 53, 55, 1, 10, 180, 100, 28904, 2701003, 5400003, 0),
    (54, 2, 99, -591.436279296875, -2599.496337890625, 1926.07568359375, 'M008_000_001_SP1', True, 'Moor Slime', '', 53, 55, 1, 10, 180, 100, 28904, 2701003, 5400003, 0),
    (55, 3, 99, -2830.73095703125, -7304.2724609375, 1972.4559326171875, 'M008_000_001_SP1', True, 'Moor Slime', '', 53, 55, 1, 10, 180, 100, 28904, 2701003, 5400003, 0),
    (56, 4, 99, -489.60211181640625, -9245.89453125, 1813.65185546875, 'M008_000_001_SP1', True, 'Moor Slime', '', 53, 55, 1, 10, 180, 100, 28904, 2701003, 5400003, 0),
    (57, 5, 99, -7006.6767578125, -4217.29833984375, 1798.2520751953125, 'M008_000_001_SP1', True, 'Moor Slime', '', 53, 55, 1, 10, 180, 100, 28904, 2701003, 5400003, 0),
    (58, 6, 99, -5154.9619140625, 1532.656982421875, 1798.2550048828125, 'M008_000_001_SP1', True, 'Moor Slime', '', 53, 55, 1, 10, 180, 100, 28904, 2701003, 5400003, 0),
    (59, 7, 99, -8246.3056640625, 2789.51416015625, 2284.1533203125, 'M008_000_001_SP1', True, 'Moor Slime', '', 53, 55, 1, 10, 180, 100, 28904, 2701003, 5400003, 0),
    (60, 1, 100, -2268.9130859375, -14867.322265625, 1987.670166015625, 'M021_000_001_SP1', True, 'Sharp snake poison ivy', '', 54, 56, 1, 16, 310, 100, 30703, 2701003, 5400003, 2802257),
    (61, 2, 100, -2268.9130859375, -19320.599609375, 1965.19140625, 'M021_000_001_SP1', True, 'Sharp snake poison ivy', '', 54, 56, 1, 16, 310, 100, 30703, 2701003, 5400003, 2802257),
    (62, 3, 100, 1381.3450927734375, -17415.1953125, 1832.9739990234375, 'M021_000_001_SP1', True, 'Sharp snake poison ivy', '', 54, 56, 1, 16, 310, 100, 30703, 2701003, 5400003, 2802257),
    (63, 4, 100, 5896.509765625, -23649.44140625, 1912.2562255859375, 'M021_000_001_SP1', True, 'Sharp snake poison ivy', '', 54, 56, 1, 16, 310, 100, 30703, 2701003, 5400003, 2802257),
    (64, 1, 98, 10743.822265625, -21253.263671875, 1794.2354736328125, 'M019_002_000_SP1', True, 'Gladiator Slave Girl', '', 52, 54, 1, 10, 290, 100, 27184, 2701003, 5400003, 0),
    (65, 2, 98, 13625.0263671875, -18248.458984375, 1960.39404296875, 'M019_002_000_SP1', True, 'Gladiator Slave Girl', '', 52, 54, 1, 10, 290, 100, 27184, 2701003, 5400003, 0),
    (66, 3, 98, 17467.4375, -17366.6328125, 1700.000244140625, 'M019_002_000_SP1', True, 'Gladiator Slave Girl', '', 52, 54, 1, 10, 290, 100, 27184, 2701003, 5400003, 0),
    (67, 4, 98, 21150.5546875, -15357.7724609375, 2160.6943359375, 'M019_002_000_SP1', True, 'Gladiator Slave Girl', '', 52, 54, 1, 10, 290, 100, 27184, 2701003, 5400003, 0),
    (68, 5, 98, 20737.2109375, -21366.607421875, 1855.518798828125, 'M019_002_000_SP1', True, 'Gladiator Slave Girl', '', 52, 54, 1, 10, 290, 100, 27184, 2701003, 5400003, 0),
    (69, 1, 103, -13705.6953125, -7340.2626953125, 1924.2117919921875, 'M023_000_001_SP3', False, 'Orc Chief ', '', 58, 60, 1, 11, 332, 100, 38728, 2701003, 5400003, 0),
    (70, 1, 102, -10406.015625, -3064.753662109375, 1798.253662109375, 'M023_000_001_SP1', True, 'Orc', '', 57, 59, 1, 16, 330, 100, 36585, 2701003, 5400003, 0),
    (71, 2, 102, -8875.796875, -7683.884765625, 2434.858154296875, 'M023_000_001_SP1', True, 'Orc', '', 57, 59, 1, 16, 330, 100, 36585, 2701003, 5400003, 0),
    (72, 3, 102, -13030.185546875, -7164.7421875, 1929.879150390625, 'M023_000_001_SP1', True, 'Orc', '', 57, 59, 1, 16, 330, 100, 36585, 2701003, 5400003, 0),
    (73, 4, 102, -15813.3466796875, -5030.9814453125, 1808.8446044921875, 'M023_000_001_SP1', True, 'Orc', '', 57, 59, 1, 16, 330, 100, 36585, 2701003, 5400003, 0),
    (74, 5, 102, -7863.27880859375, -11105.0732421875, 2302.90185546875, 'M023_000_001_SP1', True, 'Orc', '', 57, 59, 1, 16, 330, 100, 36585, 2701003, 5400003, 0),
    (75, 1, 640, -6728.8779296875, 25696.498046875, 1592.749755859375, 'P_FEMALE_003_000_ARENAFIGHTER', False, 'Crazy Rose Regina', '', 105, 110, 0, 101, 3, 150, 228055, 0, 0, 0),
    (76, 1, 641, -5997.45947265625, 25874.806640625, 1592.749755859375, 'M017_000_001_SP3', False, 'Blood dragon Norman', '', 105, 110, 0, 102, 3, 150, 228055, 0, 0, 0),
    (77, 1, 234, -12571.0126953125, 23725.578125, 1525.83642578125, 'MAP001_000_000', False, 'Mirage reel', '', 105, 110, 0, 2, 0, 150, 228055, 0, 0, 0),
    (78, 1, 235, 18659.31640625, -2653.3623046875, 4147.4521484375, 'MAP001_000_000', False, 'Mirage reel', '', 105, 110, 0, 2, 0, 150, 228055, 0, 0, 0),
    (79, 1, 236, -10272.716796875, 24037.861328125, 1557.40185546875, 'BULLETIN_BOARD', False, 'Slave Market Bulletin Board', '', 105, 110, 0, 2, 0, 150, 228055, 0, 0, 0),
    (80, 1, 744, -9832.474609375, 20201.337890625, 1558.772705078125, 'M074_000_001_N', False, 'Ventura', 'Nomad Maritime', 105, 110, 0, 2, 0, 150, 228055, 0, 0, 0),
    (81, 1, 757, -18227.58984375, 19174.37890625, 1491.3531494140625, 'P_MALE_015_000_ZERALTIN', False, 'Salahuddin', 'Liberate', 50, 50, 0, 2, 0, 150, 23976, 0, 0, 0),
    (82, 8, 519, -11667.541015625, 1527.80126953125, 2557.55078125, 'M015_001_001_SP1', False, 'Jet cat thieves No.3', '', 50, 52, 1, 16, 250, 100, 23976, 2701003, 5400003, 0),
    (83, 9, 246, 4303.18017578125, -24295.369140625, 1912.2210693359375, 'M015_001_001_SP1', False, 'Jet cat thieves No.4', '', 57, 59, 1, 16, 250, 100, 36585, 2701003, 5400003, 0),
    (115, 1, 7043, 11788.0, -20550.0, 3300.0, 'M024_001_001_SP1', True, 'Penguin Searcher', 'Serious and responsible', 99, 101, 0, 2, 0, 150, 192488, 0, 0, 0),
]

# (placement_index, set_number, mm_instance, x, y, z, reason)
UNRESOLVED_PLACEMENTS = [
    (0, 1, 1, -18724.265625, 18326.28125, 1478.566650390625, 'no_mobs_row_for_n_id_66'),
    (84, 101, 1, 14279.5205078125, 15089.09765625, 3753.29638671875, 'no_mobs_tip_row_for_n_id_10014_empty_name'),
    (85, 102, 1, 9012.47265625, -12525.39453125, 1810.40380859375, 'no_mobs_tip_row_for_n_id_10015_empty_name'),
    (86, 103, 1, -2342.21484375, -10439.4453125, 1810.40380859375, 'no_mobs_tip_row_for_n_id_10016_empty_name'),
    (87, 104, 1, 21416.435546875, -17011.46484375, 2020.343994140625, 'no_mobs_tip_row_for_n_id_10017_empty_name'),
    (88, 105, 1, 21746.189453125, 21971.4609375, 3949.51123046875, 'no_mobs_tip_row_for_n_id_10018_empty_name'),
    (89, 106, 1, -14138.4296875, 408.9609069824219, 2537.306640625, 'no_mobs_tip_row_for_n_id_10019_empty_name'),
    (90, 107, 1, -4231.21240234375, 13898.4521484375, 1980.912109375, 'no_mobs_tip_row_for_n_id_917_empty_name'),
    (91, 107, 2, -10161.26171875, 19854.73046875, 1980.4200439453125, 'no_mobs_tip_row_for_n_id_917_empty_name'),
    (92, 107, 3, -2693.166748046875, 17367.521484375, 1957.707763671875, 'no_mobs_tip_row_for_n_id_917_empty_name'),
    (93, 107, 4, -1933.017822265625, 16899.98046875, 1962.809326171875, 'no_mobs_tip_row_for_n_id_917_empty_name'),
    (94, 107, 5, -370.8133850097656, 16468.259765625, 2085.59130859375, 'no_mobs_tip_row_for_n_id_917_empty_name'),
    (95, 107, 6, -137.06509399414062, 16624.33203125, 1684.549072265625, 'no_mobs_tip_row_for_n_id_917_empty_name'),
    (96, 107, 7, -172.9010009765625, 16196.41015625, 1698.007568359375, 'no_mobs_tip_row_for_n_id_917_empty_name'),
    (97, 107, 8, -642.9832763671875, 16215.3828125, 1673.05712890625, 'no_mobs_tip_row_for_n_id_917_empty_name'),
    (98, 107, 9, -577.635498046875, 16670.708984375, 1662.619873046875, 'no_mobs_tip_row_for_n_id_917_empty_name'),
    (99, 107, 10, -1651.57421875, 16887.55859375, 1562.632080078125, 'no_mobs_tip_row_for_n_id_917_empty_name'),
    (100, 107, 11, -1968.1710205078125, 17204.158203125, 1558.807861328125, 'no_mobs_tip_row_for_n_id_917_empty_name'),
    (101, 107, 12, -2408.1865234375, 17518.0703125, 1558.7724609375, 'no_mobs_tip_row_for_n_id_917_empty_name'),
    (102, 107, 13, -2899.179931640625, 17587.828125, 1558.7724609375, 'no_mobs_tip_row_for_n_id_917_empty_name'),
    (103, 107, 14, -2939.425048828125, 17110.25, 1558.774658203125, 'no_mobs_tip_row_for_n_id_917_empty_name'),
    (104, 107, 15, -2477.945068359375, 17086.103515625, 1558.773681640625, 'no_mobs_tip_row_for_n_id_917_empty_name'),
    (105, 107, 16, -2300.86572265625, 16874.14453125, 1558.783203125, 'no_mobs_tip_row_for_n_id_917_empty_name'),
    (106, 107, 17, -1949.3897705078125, 16560.23046875, 1561.320068359375, 'no_mobs_tip_row_for_n_id_917_empty_name'),
    (107, 107, 18, -3957.544189453125, 13922.599609375, 1592.4786376953125, 'no_mobs_tip_row_for_n_id_917_empty_name'),
    (108, 107, 19, -4601.4697265625, 13898.453125, 1584.6304931640625, 'no_mobs_tip_row_for_n_id_917_empty_name'),
    (109, 107, 20, -4193.650390625, 13528.1953125, 1596.8839111328125, 'no_mobs_tip_row_for_n_id_917_empty_name'),
    (110, 107, 21, -4225.8466796875, 14215.048828125, 1579.371337890625, 'no_mobs_tip_row_for_n_id_917_empty_name'),
    (111, 107, 22, -9825.091796875, 19856.353515625, 1566.6910400390625, 'no_mobs_tip_row_for_n_id_917_empty_name'),
    (112, 107, 23, -10538.7763671875, 19877.818359375, 1612.7685546875, 'no_mobs_tip_row_for_n_id_917_empty_name'),
    (113, 107, 24, -10203.3984375, 19507.560546875, 1612.7685546875, 'no_mobs_tip_row_for_n_id_917_empty_name'),
    (114, 107, 25, -10139.005859375, 20191.732421875, 1569.8372802734375, 'no_mobs_tip_row_for_n_id_917_empty_name'),
]


class Scene4TableError(ValueError):
    """A refusal from this module, always with a reason in the message."""


@dataclass(frozen=True)
class Bg0004Placement:
    """One Bg0004 placement resolved to a real, named, bodied actor."""

    placement_index: int
    mm_instance: int
    n_id: int
    x: float
    y: float
    z: float
    visual_preset: str
    ambiguous_outfit: bool
    display_name: str
    title: str
    level: int
    level_max: int
    rank: int
    ai_wander: int
    ai_combat: int
    speed_walk: int
    max_hp: int
    drops_normal: int
    drops_equipment: int
    drops_specially: int

    @property
    def actor_identity(self) -> int:
        # Same formula bg0001/bg0002/bg0015 already use (population.py's
        # SceneActorPlacement.actor_identity) - never sent in the same
        # generation as another scene's census (each builder refuses any
        # scene id but its own), so sharing the numbering scheme is not a
        # collision in practice.
        return 0x2000 + self.placement_index + 1


@dataclass(frozen=True)
class Bg0004UnresolvedPlacement:
    """One placement this round could not, and did not, turn into an actor."""

    placement_index: int
    set_number: int
    mm_instance: int
    x: float
    y: float
    z: float
    reason: str


def _require_float32(value: Any, label: str) -> float:
    if type(value) not in (int, float) or type(value) is bool:
        raise Scene4TableError("%s must be a finite float32 value" % label)
    result = float(value)
    if not math.isfinite(result) or abs(result) > _FLOAT32_MAX:
        raise Scene4TableError("%s must be a finite float32 value" % label)
    return result


def _require_int(value: Any, label: str, low: int, high: int) -> int:
    if type(value) is not int or type(value) is bool or not low <= value <= high:
        raise Scene4TableError("%s must be an integer in [%d,%d]" % (label, low, high))
    return value


def load_known_placements() -> tuple[Bg0004Placement, ...]:
    """Type-check and return the 84 resolved placements.  No file is read."""
    if len(KNOWN_PLACEMENTS) != KNOWN_COUNT:
        raise Scene4TableError("KNOWN_PLACEMENTS count drift")
    out: list[Bg0004Placement] = []
    seen: set[int] = set()
    for row in KNOWN_PLACEMENTS:
        if type(row) is not tuple or len(row) != 20:
            raise Scene4TableError("known placement row has the wrong shape")
        (idx, mm, n_id, x, y, z, preset, ambiguous, name, title, level,
         level_max, rank, ai_wander, ai_combat, speed_walk, max_hp,
         drops_normal, drops_equipment, drops_specially) = row
        idx = _require_int(idx, "placement index", 0, TOTAL_PLACEMENT_COUNT - 1)
        if idx in seen:
            raise Scene4TableError("duplicate placement index %d" % idx)
        seen.add(idx)
        if type(preset) is not str or not preset:
            raise Scene4TableError("placement %d: visual preset must be non-empty" % idx)
        if type(name) is not str or not name:
            raise Scene4TableError("placement %d: display name must be non-empty" % idx)
        if type(ambiguous) is not bool:
            raise Scene4TableError("placement %d: ambiguous_outfit must be bool" % idx)
        out.append(Bg0004Placement(
            placement_index=idx,
            mm_instance=_require_int(mm, "mm instance", 1, 0xFFFF),
            n_id=_require_int(n_id, "n_id", 1, 0xFFFF),
            x=_require_float32(x, "placement x"),
            y=_require_float32(y, "placement y"),
            z=_require_float32(z, "placement z"),
            visual_preset=preset,
            ambiguous_outfit=ambiguous,
            display_name=name,
            title=title if type(title) is str else "",
            level=_require_int(level, "level", 1, 255),
            level_max=_require_int(level_max, "level_max", 1, 255),
            rank=_require_int(rank, "rank", 0, 0xFFFF),
            ai_wander=_require_int(ai_wander, "ai_wander", 0, 0xFFFF),
            ai_combat=_require_int(ai_combat, "ai_combat", 0, 0xFFFF),
            speed_walk=_require_int(speed_walk, "speed_walk", 0, 0xFFFF),
            max_hp=_require_int(max_hp, "max_hp", 1, 0xFFFFFFFF),
            drops_normal=_require_int(drops_normal, "drops_normal", 0, 0x7FFFFFFF),
            drops_equipment=_require_int(drops_equipment, "drops_equipment", 0, 0x7FFFFFFF),
            drops_specially=_require_int(drops_specially, "drops_specially", 0, 0x7FFFFFFF),
        ))
    return tuple(out)


def load_unresolved_placements() -> tuple[Bg0004UnresolvedPlacement, ...]:
    """Type-check and return the 32 placements this round refused to guess."""
    if len(UNRESOLVED_PLACEMENTS) != UNRESOLVED_COUNT:
        raise Scene4TableError("UNRESOLVED_PLACEMENTS count drift")
    out: list[Bg0004UnresolvedPlacement] = []
    for row in UNRESOLVED_PLACEMENTS:
        if type(row) is not tuple or len(row) != 7:
            raise Scene4TableError("unresolved placement row has the wrong shape")
        idx, set_number, mm, x, y, z, reason = row
        if type(reason) is not str or not reason:
            raise Scene4TableError("placement %d: reason must be non-empty" % idx)
        out.append(Bg0004UnresolvedPlacement(
            placement_index=_require_int(idx, "placement index", 0, TOTAL_PLACEMENT_COUNT - 1),
            set_number=_require_int(set_number, "set number", 1, 0xFFFF),
            mm_instance=_require_int(mm, "mm instance", 1, 0xFFFF),
            x=_require_float32(x, "placement x"),
            y=_require_float32(y, "placement y"),
            z=_require_float32(z, "placement z"),
            reason=reason,
        ))
    return tuple(out)


def name_template_id_mismatches() -> tuple[tuple[int, str, int], ...]:
    """The 2 rows whose own name text disagrees with the authoritative
    ``template_ids`` column (docstring step 1) - exposed as data so a test
    can hold this module to naming both rather than trusting the docstring.
    """
    return NAME_TEMPLATE_ID_MISMATCHES
