"""Bg0015 (Hell Volcano Island) census composer - LANE-A M3.

``COO-DECISION 2026-08-28T22:50+07:00`` ruled that the owner's pause on M2
covers ``BUILD-002``'s sea/boat travel and nothing else, and told this lane to
build the part of M3 that does not go through that door: this scene's
population, server side, entered for a test round by a GM warp or a direct
scene set.  Not one line here is about travel.

THE SIBLING PATTERN, NOT A FORK.  ``world_population`` builds bg0001's census
and refuses anywhere but scene 1; ``world_population_bg0002`` is the same
shape for scene 2.  This is the third: it refuses anywhere but scene 14, over
``world_bg0015_identity``'s 81 shippable placements of 91.  Every wire call
below is the exact frozen serializer the other two already use
(``legacy.make_npc_attr`` / ``make_remote_movement_attr`` /
``make_remote_actor_entry`` / ``make_runtime_remote_actors``), and the wire
header constants and the accepted initial+reapply schedule are IMPORTED from
``world_population`` rather than redefined -- they describe the wire format,
which is not scene-specific.

WHAT IS DIFFERENT FROM THE OTHER TWO, NAMED RATHER THAN LEFT IMPLICIT.

* This is a FIELD scene, so most of its cast are monsters: 105-level Hell
  Ghouls, Blood red eagles, Earth Flame Dragons and so on (see
  ``world_bg0015_identity``'s docstring for the roster and the four controls
  under it).  They are sent here as NAMED, BODIED, NEUTRAL actors with real
  HP -- there is no faction bit on any entry in this module.  Making them
  hostile is lane B's splice (its hostile-monster module and ``mob_death``
  widen the BasicAttr mask), deliberately not done here: a wrong identity that a player
  can walk up to and read is recoverable, and a wrong identity that attacks
  them on sight is not.  A round that wants both should land this one first.
* HP is real and comes from the table chain, not composed:
  ``STANDARD_MOB[MOBS.n_LEVEL_MIN].n_HPMAX``, the same derivation lane B's
  ``field_mob_tables`` uses.  Sent as current == max (alive), matching
  ``world_population``'s own "no half-dead spawn" convention.
* ~~THE COLLISION WITH LANE B'S MINED HOSTILE ROSTER FOR THIS SAME SCENE,
  which is already at HEAD and which this module's first draft did not open
  (pf-adversary, round
  w0pu2i - and it is the G1 failure by name: the repo's own artifact for
  this exact scene went unread).  That module is lane B's mined hostile
  roster for the SAME scene, generated by a rule that reads the Mob-Set
  number straight as a ``MOBS.n_ID`` - the reading GT-078 had rejected.  It
  and this module both compute ``actor_identity = 0x2000 + placement_index
  + 1``, both for scene 14, and 16 of its 17 placement indices are indices
  this module also ships.  Placement 61 is "Fighting Fish soldier, lv25,
  hp3138" there and "Hell Ghoul, lv105, hp228055" here, at the same identity
  and the same XYZ.~~  ~~``world_bg0015_identity.COLLIDING_PLACEMENTS`` names
  the sixteen overlapping placements (computed and asserted in
  ``tests/test_world_bg0015_identity.py`` ...)~~
  **THE COLLISION IS DORMANT, NOT RESOLVED - AND THE FIRST REWRITE OF THIS
  PARAGRAPH GOT THAT WRONG TOO.**  The struck text above was false at HEAD;
  so was the correction that first replaced it, which said "THE COLLISION IS
  GONE" and claimed placement 61 was "no longer in lane B's table in any
  form" and that one of the sixteen was "still in lane B's table at all".
  pf-adversary measured both false before either reached ``main`` (round
  8ubiku, D4).  Both versions are kept, struck, because two wrong readings
  of the same table in two consecutive rounds is the thing worth recording.

  What is true at HEAD, re-derived by this lane rather than taken from lane
  B's letter (``notes_to_chief/20260829_0605_LANE-B-STATUS-bg0015-collision-
  is-gone-and-lane-A-test-moved.md``):

    - The two tables share **12** placements (22, 24, 27, 29, 31, 44, 45,
      46, 47, 51, 70, 87) and **agree on all 12** - same ``MOBS.n_ID``, same
      name, and same XYZ to the float.  That part of lane B's letter holds
      up, and this lane's own test now pins the XYZ leg lane B did not.
    - **All sixteen** members of ``COLLIDING_PLACEMENTS`` are still in lane
      B's module.  Exactly one (placement **70**) is still SHIPPED; the
      other fifteen appear in ``WITHDRAWN_UNDER_THIS_RULE`` AND AGAIN in
      ``UNRESOLVED_PLACEMENTS`` - the two lists duplicate here rather than
      partitioning, which the first draft of this sentence read as a split
      (pf-adversary, round 8ubiku2, E14).  Placement 61 is one of them,
      verbatim.
      "Still in the table" and "still shipped" are different claims and the
      first rewrite widened one into the other.
    - **AND THAT IS THE POINT.  The overlap did not disappear because the
      two tables came to agree about those fifteen placements.  It
      disappeared because lane B STOPPED SHIPPING them** - every withdrawn
      row carries the reason ``[not carried: n_id_35x_avatar_is_a_variant_
      list]``.  The identity question for those fifteen is not settled, it
      is unasked.  **The day lane B can carry variant lists, fifteen
      placements come back and the collision returns with them**, and
      nothing in either module would announce that.

  So the RE-092 replace-by-omission hazard survives, for a reason narrower
  than the struck text gave: this module computes ``actor_identity = 0x2000
  + placement_index + 1`` for scene 14, lane B's table is built for the same
  scene on the same convention, and two collections still cannot both be
  sent.  ~~both modules compute~~ - only this one computes it; lane B's
  module names the formula in a comment about its downstream callers and is
  imported by no non-test file in this repository at all (D5).  That makes
  the hazard a future one rather than a present one, which is worth saying
  precisely, because "there are two senders today" would be false.  This
  lane does not edit lane B's file, and does not even name it under
  ``src/``: a guard test forbids any mention of that name here, and it is
  right to.
* Ten of the 91 placements are dropped because their Mob-Set number has no
  shippable identity.  The console line prints ``assembled=81/91`` every
  boot and ``unresolved=10``; ``world_bg0015_identity.unshippable_placements``
  names which ten and why.  The 91 target is never quietly rewritten
  (CHARTER-02).

~~THE HANDBACK, STATED PLAINLY BECAUSE IT IS THIS ROUND'S REAL LIMIT.
Nothing in this repository calls this module yet.~~  STRUCK ROUND ucaybn: it
HAS a caller - ``lane_hooks/lane_a_scene_census.py`` (round ga91m5-r2),
reaching this builder through ``world_population_handoff``.  The paragraph
below is kept because it is the exact shape of the wall, and because what
came down was its SECOND sentence, not its first: chief did not add a
scene-14 ``elif``.  chief added ONE table-driven point in round ``73fhoc``
and the lane registered on it.  "``fire()`` cannot contribute the actions a
census dispatch returns" was right, which is why the point that landed hands
a value back instead.  What is still true: no human has stood in scene 14,
its door is pinned shut (``login_entry_allowed: false``), and ``GT-134`` is
the ticket that opens the eye.  The original text follows.

~~Nothing in this repository calls this module yet.~~  ``runtime.py``'s census dispatch is
an if/elif over scene id -- bg0002, then "any other scene: send NOTHING", then
bg0001 -- and adding scene 14 to it is a ``runtime.py`` edit, which is the
chief's file, not this lane's.  ``lane_hooks`` cannot stand in for it either:
its two existing points are both inbound-vital points, ``fire()`` is
report-only by contract and cannot contribute the actions a census dispatch
returns.  So until one of those two things lands, a player warped into this
scene sees an empty island and this module is dead code that passes its
tests.  The one-line request is in this round's PR body and in
``notes_to_chief/20260828_2348_LANE-A-CORE-REQUEST-bg0015-census-branch.md``.

WHAT THIS MODULE DOES NOT CLAIM.  Everything ``world_bg0015_identity``'s
"WHAT THIS MODULE DOES NOT CLAIM" says, unchanged, and one more: no human has
ever seen this scene in this project, so there is no client-observable layer
under any of it.  ``GT-134`` is the ticket that opens one.  Until it comes
back, ``census_console_line`` and ``actor_lines`` are wire/DB-layer evidence
and nothing above that.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from . import world_bg0015_identity as identity
from . import world_population
from .population import (
    FULL_MOVEMENT_MASK,
    MOVEMENT_ATTR_ID,
    NPC_ATTR_ID,
    NPC_STYLE_ACTOR_TYPE,
)


# Convention marker only: nothing branches on it and no chief-owned file
# imports this module yet.  See the handback above before reading this as
# "live today".
production_allowed = True
test_only = False

SCENE_N_ID = identity.SCENE_N_ID
SCENE_SEQUENCE = 0
ROSTER_COUNT = len(identity.shippable_placements())
PLACEMENT_COUNT = identity.PLACEMENT_COUNT
UNRESOLVED_COUNT = PLACEMENT_COUNT - ROSTER_COUNT
DEFAULT_ACTOR_COUNT = ROSTER_COUNT

WIRE_HEADER_BYTES = world_population.WIRE_HEADER_BYTES
WIRE_COUNT_TAG_OFFSET = world_population.WIRE_COUNT_TAG_OFFSET
COLLECTION_TAG = world_population.COLLECTION_TAG
INITIAL_REAPPLY_MS = world_population.INITIAL_REAPPLY_MS

COUNT_SOURCE_FULL_ROSTER = "bg0015_full_roster"
COUNT_SOURCE_CALLER = "caller_requested"
COUNT_SOURCES = (COUNT_SOURCE_FULL_ROSTER, COUNT_SOURCE_CALLER)


class Bg0015CensusError(ValueError):
    """A refusal from this module, always with a reason in the message."""


@dataclass(frozen=True)
class Bg0015PopulationGeneration:
    """One built Bg0015 collection: its membership, its bytes, nothing sent."""

    actor_count: int
    placement_indices: tuple[int, ...]
    actor_identities: tuple[int, ...]
    n_ids: tuple[int, ...]
    display_names: tuple[str, ...]
    anchor: tuple[float, float, float]
    pc: bytes
    frame: bytes
    entry_bytes: tuple[int, ...] = ()
    count_source: str = COUNT_SOURCE_CALLER

    @property
    def pc_bytes(self) -> int:
        return len(self.pc)

    @property
    def frame_bytes(self) -> int:
        return len(self.frame)


def _require_anchor(player_xyz: Any) -> tuple[float, float, float]:
    if type(player_xyz) is not tuple or len(player_xyz) != 3:
        raise Bg0015CensusError("player XYZ must be an exact three-value tuple")
    import math
    checked = []
    for axis, value in zip("xyz", player_xyz):
        if type(value) not in (int, float) or type(value) is bool:
            raise Bg0015CensusError(
                "player %s must be a finite float32 value" % axis)
        result = float(value)
        if not math.isfinite(result) or abs(result) > 3.4028234663852886e38:
            raise Bg0015CensusError(
                "player %s must be a finite float32 value" % axis)
        checked.append(result)
    return (checked[0], checked[1], checked[2])


def _require_actor_count(actor_count: Any) -> int:
    if type(actor_count) is not int or type(actor_count) is bool or not (
        1 <= actor_count <= ROSTER_COUNT
    ):
        raise Bg0015CensusError(
            "actor count must be an integer in [1,%d]" % ROSTER_COUNT)
    return actor_count


def census_order(
    player_xyz: tuple[float, float, float],
) -> tuple[identity.Bg0015Placement, ...]:
    """The 81 shippable placements, nearest the anchor first.

    Nearest-first is the same order the other two censuses use, and it is
    what makes a truncated count (a caller asking for fewer than the whole
    roster) show the player the actors around them rather than an arbitrary
    slice of the island.  ``shippable_placements`` has already dropped the
    ten with no identity; this only orders what it returned.
    """
    x, y, z = _require_anchor(player_xyz)
    ordered = sorted(
        identity.shippable_placements(),
        key=lambda p: (
            (p.x - x) ** 2 + (p.y - y) ** 2 + (p.z - z) ** 2,
            p.placement_index,
        ),
    )
    return tuple(ordered)


def _entry(legacy: Any, placement: identity.Bg0015Placement) -> bytes:
    """One actor entry: the same frozen shape the other two censuses build.

    The first ``make_npc_attr`` parameter is the serializer's own
    "MOBS/template u16 at +0x78", and what goes into it is the REAL
    ``MOBS.n_ID`` from the CLINE crosswalk -- never the Mob-Set number, which
    is the exact mistake ``GT-078`` put on the owner's screen for bg0001.

    HEADING.  This scene's placement rows carry no heading column either (the
    same three f32 that ``world_population_bg0002``'s ``_entry`` measured as
    a radius-shaped triple, not a rotation), so this reuses
    ``world_population.HEADINGS`` on the placement index exactly as both
    other scenes do rather than inventing a second heading policy.
    """
    npc_attr = legacy.make_npc_attr(
        placement.n_id,
        placement.actor_identity,
        SCENE_N_ID,
        SCENE_SEQUENCE,
        placement.visual_preset,
        current_hp=placement.max_hp,
        max_hp=placement.max_hp,
        basic_name=placement.display_name,
    )
    movement_attr = legacy.make_remote_movement_attr(
        placement.actor_identity,
        placement.x, placement.y, placement.z,
        world_population.HEADINGS[placement.placement_index & 3],
        mask=FULL_MOVEMENT_MASK,
    )
    return legacy.make_remote_actor_entry(
        NPC_STYLE_ACTOR_TYPE,
        placement.actor_identity,
        [(NPC_ATTR_ID, npc_attr), (MOVEMENT_ATTR_ID, movement_attr)],
    )


def build_bg0015_population(
    legacy: Any,
    player_xyz: tuple[float, float, float],
    actor_count: int = DEFAULT_ACTOR_COUNT,
    *,
    scene_id: int,
    count_source: str = COUNT_SOURCE_CALLER,
) -> Bg0015PopulationGeneration:
    """Build the Bg0015 roster as ONE RuntimeRes collection.  Sends nothing.

    ``scene_id`` has no default on purpose, the same reason the other two
    builders give: every actor in this table is encoded with scene 14, and a
    caller that forgets which scene it is in would deliver volcano monsters
    into a town.  Refuses anywhere but scene 14.
    """
    if type(scene_id) is not int or scene_id != SCENE_N_ID:
        raise Bg0015CensusError(
            "the Bg0015 roster is only valid in scene %d, not scene %r"
            % (SCENE_N_ID, scene_id))
    if count_source not in COUNT_SOURCES:
        raise Bg0015CensusError("unknown count source %r" % count_source)
    count = _require_actor_count(actor_count)
    # pf-adversary, round w0pu2i: without this, a caller can build a
    # five-actor census, label it "full roster", and the console line prints
    # ``assembled=5/91 source=bg0015_full_roster`` with 76 of 91 unexplained.
    # ``count_source`` was a caller assertion the report presented as
    # provenance.  Now the two have to agree or nothing is built.
    if count_source == COUNT_SOURCE_FULL_ROSTER and count != ROSTER_COUNT:
        raise Bg0015CensusError(
            "count source %r claims the whole roster but the count is %d, "
            "not %d" % (count_source, count, ROSTER_COUNT))
    ordered = census_order(player_xyz)[:count]
    entries = [_entry(legacy, placement) for placement in ordered]
    for position, entry in enumerate(entries):
        if type(entry) is not bytes or not entry:
            raise Bg0015CensusError(
                "placement %d (n_id %d) encoded to an empty actor entry"
                % (ordered[position].placement_index, ordered[position].n_id))
    pc, frame = legacy.make_runtime_remote_actors(entries)
    return Bg0015PopulationGeneration(
        count,
        tuple(p.placement_index for p in ordered),
        tuple(p.actor_identity for p in ordered),
        tuple(p.n_id for p in ordered),
        tuple(p.display_name for p in ordered),
        _require_anchor(player_xyz),
        pc,
        frame,
        tuple(len(entry) for entry in entries),
        count_source,
    )


def wire_actor_count(generation: Bg0015PopulationGeneration) -> int:
    """Read the collection count back out of the bytes that will be sent."""
    if type(generation) is not Bg0015PopulationGeneration:
        raise Bg0015CensusError(
            "wire actor count needs a Bg0015PopulationGeneration")
    pc = generation.pc
    if len(pc) < WIRE_HEADER_BYTES or pc[WIRE_COUNT_TAG_OFFSET] != COLLECTION_TAG:
        raise Bg0015CensusError(
            "built frame does not carry the expected collection header")
    return int.from_bytes(
        pc[WIRE_COUNT_TAG_OFFSET + 1:WIRE_COUNT_TAG_OFFSET + 3], "little")


def dispatch_report(generation: Bg0015PopulationGeneration) -> dict:
    """Count what assembled BEFORE it goes out, cross-checked against the bytes.

    The same three numbers the other two censuses report, and for the same
    reason: what was assembled, what the wire header says, and whether the
    body bytes really total that many entries.  A header that disagrees with
    the bodies is how this project earns ``ErrorData=28317``.

    ``shortfall_reason`` is read off what was actually available to send, not
    guessed from ``count != requested`` -- the correction pf-adversary forced
    on bg0001's report last round, applied here from the start.
    """
    if type(generation) is not Bg0015PopulationGeneration:
        raise Bg0015CensusError(
            "dispatch report needs a Bg0015PopulationGeneration")
    assembled = len(generation.placement_indices)
    declared = wire_actor_count(generation)
    body_bytes = generation.pc_bytes - WIRE_HEADER_BYTES
    entry_bytes_total = sum(generation.entry_bytes)
    bodies_intact = (
        bool(generation.entry_bytes)
        and len(generation.entry_bytes) == assembled
        and body_bytes == entry_bytes_total
        and all(generation.entry_bytes)
    )
    shortfall_reason = None
    if assembled != ROSTER_COUNT:
        shortfall_reason = "%s=%d" % (generation.count_source, assembled)
    elif assembled != PLACEMENT_COUNT:
        shortfall_reason = "identity_unresolved=%d" % UNRESOLVED_COUNT
    return {
        "assembled_count": assembled,
        "wire_actor_count": declared,
        "roster_count": ROSTER_COUNT,
        "placement_count": PLACEMENT_COUNT,
        "unresolved_count": UNRESOLVED_COUNT,
        "count_source": generation.count_source,
        "shortfall_reason": shortfall_reason,
        "counts_agree": declared == assembled,
        "bodies_intact": bodies_intact,
        "body_bytes": body_bytes,
        "entry_bytes_total": entry_bytes_total,
        "pc_bytes": generation.pc_bytes,
        "frame_bytes": generation.frame_bytes,
        "anchor": list(generation.anchor),
        "initial_reapply_ms": INITIAL_REAPPLY_MS,
    }


def census_console_line(generation: Bg0015PopulationGeneration) -> str:
    """The one grep-able ``WORLD_CENSUS`` line a boot in this scene prints.

    ``assembled=N/91`` against the scene's REAL placement count, not against
    the 81 that happen to resolve, so a reader sees the shortfall without
    having to know this module's internals.  ASCII only (bridge console is
    cp874).
    """
    report = dispatch_report(generation)
    return (
        "WORLD_CENSUS_BG0015 assembled={0}/{1} shippable={2} wire={3} "
        "bodies={4} pc={5}B frame={6}B anchor=({7:.3f},{8:.3f},{9:.3f}) "
        "reapply_ms={10} source={11} shortfall={12} unresolved={13}".format(
            report["assembled_count"], report["placement_count"],
            report["roster_count"],
            report["wire_actor_count"] if report["counts_agree"]
            else "MISMATCH:%d" % report["wire_actor_count"],
            "ok" if report["bodies_intact"] else "SHORT",
            report["pc_bytes"], report["frame_bytes"],
            report["anchor"][0], report["anchor"][1], report["anchor"][2],
            report["initial_reapply_ms"], report["count_source"],
            report["shortfall_reason"] or "none",
            report["unresolved_count"],
        )
    )


def actor_lines(generation: Bg0015PopulationGeneration) -> tuple[str, ...]:
    """One ASCII line per actor: ``n_ID name level @x,y,z``.

    The headless half of the two-layer evidence rule: a grader can read who
    this census says is standing where, without a client.  Every name in the
    shipped table is ASCII by ``world_bg0015_identity._self_check``, so no
    escaping is invented here.
    """
    if type(generation) is not Bg0015PopulationGeneration:
        raise Bg0015CensusError("actor lines need a Bg0015PopulationGeneration")
    placements = {p.placement_index: p
                  for p in identity.shippable_placements()}
    lines = []
    for index in generation.placement_indices:
        placement = placements[index]
        lines.append(
            "n_ID=%d %s lv%d hp%d @(%.3f,%.3f,%.3f)"
            % (placement.n_id, placement.display_name,
               placement.identity.level, placement.max_hp,
               placement.x, placement.y, placement.z))
    return tuple(lines)


def unresolved_lines() -> tuple[str, ...]:
    """One ASCII line per DROPPED placement, with the reason.

    CHARTER-02's rule in executable form: a shortfall is reported with the
    real number and the real reason, in the same console output as the
    census, rather than left for someone to notice as a missing actor.
    """
    return tuple(
        "BG0015_UNSHIPPED placement=%d set=%d cline_row=%d leader_n_id=%d "
        "reason=%s"
        % (row["placement_index"], row["template_id"], row["cline_row_id"],
           row["leader_n_id"], row["reason"].replace(" ", "_"))
        for row in identity.unshippable_placements()
    )


def census_console_lines(
    legacy: Any, player_xyz: tuple[float, float, float]
) -> tuple[str, ...]:
    """``WORLD_CENSUS_BG0015`` + one line per actor + one per dropped one.

    Everything a headless proof for this scene needs, in one call, built from
    ONE generation (never composing the roster twice).  Deliberately does NOT
    print a ``WORLD_SCENE`` line the way bg0002's helper does:
    ``world_scene_travel``'s registry has no pinned destination for scene 14
    and this lane will not invent one -- pinning it needs the scene's native
    ``.npc`` digest, which is not in this clone (only the extracted TSV is).
    That request is in this round's letter, not papered over here.
    """
    generation = build_bg0015_population(
        legacy, player_xyz, scene_id=SCENE_N_ID,
        count_source=COUNT_SOURCE_FULL_ROSTER,
    )
    return (
        (census_console_line(generation),)
        + actor_lines(generation)
        + unresolved_lines()
    )
