"""The 160-name server API surface the game's own Lua scripts call.

WHERE THIS COMES FROM.  ``api_spec.tsv`` beside this file is a frozen copy of
five columns (namespace, method, call_count, file_count, arity_min,
arity_max) taken from ``pf_bridge/gamedata/PF_GAMEDATA_LUA_API.tsv`` on
2026-09-05, which is itself generated by ``gamedata/pf_lua_api_census.py``
scanning the 616 shipped ``.lua`` files.  That census is LANE-Q's charter
(``prompts/LANE-Q.md``); this module is the vendored, dependency-free copy a
fresh clone of THIS repository needs so tests here never require a sibling
``pf_bridge`` checkout to know the shape of the API surface.

Nothing here is copied by hand: every row is one line straight out of the
TSV, so a re-vendor is a diff, not a retype.  If the count drifts (a new
game script pass finds more callers, or a rescan changes an arity), this
file's own count assertions in ``tests/test_script_lua_api_spec.py`` will
say so on the very next run, on any machine, without a sibling checkout.

LOADED ON FIRST USE, NOT AT IMPORT (pf-adversary finding 13, round
``8ou0zg``, paid in round ``oghyca``).  The parse used to run at this
module's own import, which had one consequence no amount of care inside
:func:`_load` could repair: ``script_host`` imports this module, so a
corrupt ``api_spec.tsv`` made ``import script_host`` itself raise, before
any of that module's fail-closed sweeps -- or
``script_host._host_side_error_types()``, whose whole job is to keep a
defect of OURS from being logged against a shipped quest script -- existed
to see it.  The one mirror every ``ScriptHost`` construction depends on was
the one mirror whose failure could never be classified.

Now the parse happens on first ATTRIBUTE ACCESS instead, so it lands inside
``load_script_file``'s own try, gets the ``LUA_HOST ... discovered_at=<file>``
line, and is counted in the sweep's ``host_failed`` bucket like every other
mirror of ours.

HOW FAR THAT IS MEASURED (pf-adversary D2/D7, round ``oghyca``, paid in
round ``5qtaqy``).  Round ``oghyca`` wrote "measured end to end" here.  What
the sweep test ``BrokenApiSpecIsOursNotTheScriptsTests``
(``tests/test_script_lua_corpus.py``) actually drives is ONE shape -- the
file missing entirely -- and that shape was the only one this module could
detect at all: a census whose CONTENT was wrong parsed happily, and the
names it lost then reached the scripts as ``ApiNamespaceStub``'s numeric
default, so ``Player.RemoveItem`` with a trailing space in one cell
produced 189 ``LUA_SCRIPT ... attempt to call a number value`` lines across
122 innocent quest files and not one ``LUA_HOST`` line.  The refusals in
:func:`_load` below (identifier-shaped cells, digits-only counts, no
duplicate qualified name, and a digest over the file's own body) are what
turns a corrupt census back into a defect of OURS, and
``ACorruptCensusIsRefusedNotSilentlyLostTests`` in
``tests/test_script_lua_api_spec.py`` is what measures each of them.

Call sites are unchanged: the module-level names below still read as
plain attributes, resolved through PEP 562 ``__getattr__``.

``__all__`` is declared for the same reason the lazy names are listed
rather than inferred: ``from ...spec import *`` reads ``__dict__``, not
``__dir__``, so without it a star-import handed out ``Path``, ``threading``
and ``dataclass`` and NONE of the four names this module exists to
publish.  (What ``__all__`` does not fix, and what no module-level
``__getattr__`` can: ``getattr(spec, "API_FUNCTIONS", default)`` and
``hasattr`` RAISE :class:`VendoredDataError` when the mirror is corrupt
instead of returning the default -- a tool that walks modules dies mid
report rather than skipping.  That is the correct failure for this mirror
-- silence is what D2 punished -- but it is a shape a caller must know
about, so it is written down rather than discovered.)
"""
from __future__ import annotations

import threading
from dataclasses import dataclass
from pathlib import Path

from .vendored import VendoredDataError

_SPEC_PATH = Path(__file__).with_name("api_spec.tsv")

#: The header this module was written against, in order.
_HEADER = (
    "namespace", "method", "call_count", "file_count",
    "arity_min", "arity_max",
)


@dataclass(frozen=True)
class ApiFunction:
    namespace: str
    method: str
    call_count: int
    file_count: int
    arity_min: int
    arity_max: int

    @property
    def qualified_name(self) -> str:
        return "%s.%s" % (self.namespace, self.method)


#: The comment line carrying a digest of this file's OWN body.  Same
#: spelling as ``message_catalog.tsv`` and ``quest_criteria_rows.tsv``, so
#: one habit covers all three mirrors.
BODY_DIGEST_PREFIX = "# body_sha256: "


def body_digest(text: str) -> str:
    """sha256 over every line of the mirror that is not a ``#`` comment.

    Same helper shape (and same purpose) as ``lua_api.message.body_digest``
    and ``lua_api.quest_criteria.body_digest``: checkable on the Windows
    gate, which has no ``pf_bridge`` source table beside it to diff
    against.  Kept local rather than imported so a corrupt message catalog
    and a corrupt census cannot take each other down.
    """
    import hashlib

    body = "".join(line + "\n" for line in text.splitlines()
                   if not line.startswith("#"))
    return hashlib.sha256(body.encode("ascii")).hexdigest()


def _load(path: Path = _SPEC_PATH) -> tuple[ApiFunction, ...]:
    """Parse ``api_spec.tsv``, refusing loudly on anything it is not.

    ``path`` defaults to the vendored file beside this module and exists so
    the refusals below can be exercised against a corrupt COPY without
    touching the real one -- in particular from a child interpreter running
    under ``-O``, which is the only way to prove the guard survives
    optimisation.  The first attempt at those tests copied the whole 21 MB
    ``src/`` tree per test instead; on the Windows gate that is 126 MB of
    file copying plus an ``rmtree`` over a tree a child interpreter has just
    written ``__pycache__`` into, and the gate went RED at ``pytest_subset``
    with no FAILED line.  A parameter is cheaper and says more.

    RAISES, NEVER ASSERTS (pf-adversary D13, round ``wn088m``).  The header
    check used to be a bare ``assert``, which ``python -O`` DELETES: under
    ``-O`` a re-vendor that reordered the columns would have been parsed
    happily, silently swapping ``call_count`` with ``file_count`` for all
    160 rows -- the guard would not have failed, it would not have existed.
    Every refusal here names the file and, where there is one, the line.

    :class:`~lua_api.vendored.VendoredDataError` rather than a bespoke
    class, so that wherever this error IS catchable it is classified as a
    corrupt mirror of ours rather than a broken quest file.

    WHERE THIS IS CAUGHT (round ``oghyca``, scope corrected in ``5qtaqy``).
    Round ``wn088m`` corrected an earlier draft of this docstring that
    claimed ``script_host`` reports this as ``LUA_HOST``: at the time it
    could not, because this function ran at IMPORT time and took ``import
    script_host`` down with it before ``_host_side_error_types()`` existed
    to classify anything.  That is no longer the shape -- see this module's
    own docstring -- so the claim is true again.  What is MEASURED end to
    end through a real sweep is the file-missing shape
    (``BrokenApiSpecIsOursNotTheScriptsTests``,
    ``tests/test_script_lua_corpus.py``); the content-corruption shapes are
    measured against this function directly, one test per refusal, in
    ``ACorruptCensusIsRefusedNotSilentlyLostTests``.  Both are refusals of
    the same class from the same function, so both reach the same bucket --
    but only the first has been driven through 616 files, and round
    ``oghyca`` claimed more than that.

    WHAT A REFUSAL IS FOR (pf-adversary D2, round ``oghyca``).  Anything
    this function accepts becomes the census, and any NAME the census loses
    stops being an API: ``ApiNamespaceStub.__getitem__`` hands an unlisted
    name ``STUB_DEFAULT`` (the integer 0) rather than nil, so the script's
    ``Player.RemoveItem(...)`` becomes "attempt to call a number value" --
    a ``LUA_SCRIPT`` line blaming a quest file for a defect of ours.
    Measured: one trailing space after ``RemoveItem`` in one cell, invisible
    in a diff, produced 189 such lines over 122 innocent files, zero
    ``LUA_HOST`` lines, and 18/18 green in
    ``tests/test_script_lua_api_spec.py``.  So a cell that is not shaped
    like the identifier a script indexes is refused HERE, where it is one
    error naming one line, instead of being handed to 616 scripts as a
    number.  The same reasoning covers a duplicate qualified name (which
    silently shrank ``BY_QUALIFIED_NAME`` to 159 while ``API_FUNCTIONS``
    stayed 160), counts that only ``int()`` would accept (``3_67``,
    ``+367``, ``"  367  "``), and an arity range that runs backwards.

    THE DIGEST IS THE ONE CHECK THAT DOES NOT NEED TO GUESS.  Every refusal
    above is a rule about what a corrupt row LOOKS like.  The
    ``# body_sha256:`` header, same shape as ``message_catalog.tsv`` and
    ``quest_criteria_rows.tsv``, is the check that needs no imagination: a
    re-vendor that changes any header or row byte and does not recompute
    the digest is refused whatever it looks like.  A re-vendor recomputes it
    with, from the repository root, ``PYTHONPATH=src python3 -c "from
    pirateforce_foundation.lua_api import spec;
    print(spec.body_digest(open(spec._SPEC_PATH).read()))"`` -- the
    ``PYTHONPATH`` is not decoration, the command does not run without it,
    and a recompute command that does not run is how a digest header goes
    stale.
    """
    try:
        text = path.read_text(encoding="ascii")
    except OSError as exc:
        raise VendoredDataError(
            "cannot read %s: %s" % (path, exc)) from exc
    except UnicodeDecodeError as exc:
        raise VendoredDataError(
            "%s is not ASCII: %s" % (path, exc)) from exc
    lines = text.splitlines()
    if not lines:
        raise VendoredDataError("%s is empty" % (path,))

    declared = None
    for line in lines:
        if line.startswith(BODY_DIGEST_PREFIX):
            declared = line[len(BODY_DIGEST_PREFIX):].strip()
            break
    if declared is None:
        raise VendoredDataError(
            "%s has no %s header" % (path, BODY_DIGEST_PREFIX.strip()))
    actual = body_digest(text)
    if declared != actual:
        raise VendoredDataError(
            "%s body digest mismatch (header %s, body %s): the file was "
            "hand-edited, truncated, or re-vendored without recomputing "
            "the digest" % (path, declared, actual))

    #: Line numbers are the FILE's, not the body's, so an error message
    #: names the line an editor would jump to.
    numbered = [(lineno, line) for lineno, line in enumerate(lines, start=1)
                if not line.startswith("#")]
    if not numbered:
        raise VendoredDataError("%s has no rows outside its comments" % (path,))
    header = tuple(numbered[0][1].split("\t"))
    if header != _HEADER:
        raise VendoredDataError(
            "%s header drifted: got %r, want %r"
            % (path, header, _HEADER))
    out = []
    seen: dict = {}
    for lineno, line in numbered[1:]:
        if not line:
            continue
        cells = line.split("\t")
        if len(cells) != len(_HEADER):
            raise VendoredDataError(
                "%s line %d has %d columns, want %d: %r"
                % (path, lineno, len(cells), len(_HEADER), line))
        ns, method, call_count, file_count, arity_min, arity_max = cells
        for column, cell in (("namespace", ns), ("method", method)):
            # `isidentifier` and not a regex or a `strip()`: this is the
            # exact shape a Lua script indexes the namespace by, so a cell
            # that fails it is a name no script can ever reach.  It also
            # rejects the empty cell for free.
            if not cell.isidentifier():
                raise VendoredDataError(
                    "%s line %d has a %s that is not an identifier: %r"
                    % (path, lineno, column, cell))
        numbers = []
        for column, cell in (("call_count", call_count),
                             ("file_count", file_count),
                             ("arity_min", arity_min),
                             ("arity_max", arity_max)):
            # `int()` alone accepts `3_67`, `+367`, and `"  367  "` -- three
            # spellings a re-vendor could produce and no counting tool
            # means.  A count column is digits and nothing else.
            if not cell.isdigit():
                raise VendoredDataError(
                    "%s line %d has a non-integer count in %s: %r"
                    % (path, lineno, column, cell))
            numbers.append(int(cell))
        if numbers[2] > numbers[3]:
            raise VendoredDataError(
                "%s line %d has arity_min %d greater than arity_max %d"
                % (path, lineno, numbers[2], numbers[3]))
        qualified = "%s.%s" % (ns, method)
        if qualified in seen:
            raise VendoredDataError(
                "%s line %d repeats the qualified name %r first seen on "
                "line %d" % (path, lineno, qualified, seen[qualified]))
        seen[qualified] = lineno
        out.append(ApiFunction(
            namespace=ns,
            method=method,
            call_count=numbers[0],
            file_count=numbers[1],
            arity_min=numbers[2],
            arity_max=numbers[3],
        ))
    if not out:
        raise VendoredDataError("%s has a header and no rows" % (path,))
    return tuple(out)


_LOCK = threading.RLock()
_CACHE: dict = {}


def _tables() -> dict:
    """Parse the census once, then hand back the same tables forever.

    WHY THE LOCK, ACCURATELY (pf-adversary D7.3, round ``oghyca``, corrected
    in ``5qtaqy``).  Round ``oghyca`` justified this lock by saying "a corpus
    sweep and the future live dispatch both reach this from whichever thread
    touched a script first".  Measured, that was two claims and neither
    holds today: ``run_corpus_entry_points`` is a single-threaded ``for``
    loop, and there is no live dispatch anywhere in ``src/`` yet.  No test
    drives this lock; removing it leaves the suite green.  What IS measured
    is that it works if a second thread ever arrives: 16 threads calling
    ``_tables()`` after ``_CACHE.clear()`` get one and the same object, and
    the double-checked first read keeps the steady state off the lock.  So
    the lock stays -- a mirror every ``ScriptHost`` construction reads is
    the wrong place to find out -- but it stays as **[PROPOSED]**
    protection against a caller this repository has not written yet, not as
    a description of one it has.

    ``_CACHE`` is a dict rather than four module globals so a test can point
    ``_SPEC_PATH`` somewhere else and call ``_CACHE.clear()`` in one line,
    with no chance of clearing three of four.
    """
    tables = _CACHE.get("tables")
    if tables is not None:
        return tables
    with _LOCK:
        tables = _CACHE.get("tables")
        if tables is None:
            functions = _load(_SPEC_PATH)
            methods: dict = {}
            for fn in functions:
                methods.setdefault(fn.namespace, set()).add(fn.method)
            #: namespace -> frozenset of its method names, e.g. ["Quest"].
            namespace_methods = {k: frozenset(v) for k, v in methods.items()}
            tables = {
                # Every row of the frozen census, in file order.
                "API_FUNCTIONS": functions,
                "NAMESPACE_METHODS": namespace_methods,
                # The 8 namespace names the scripts index as Lua globals.
                "NAMESPACES": tuple(sorted(namespace_methods)),
                # qualified name ("Quest.SetFlag") -> ApiFunction.
                "BY_QUALIFIED_NAME": {
                    fn.qualified_name: fn for fn in functions},
            }
            _CACHE["tables"] = tables
    return tables


#: The module-level names this module has always exposed.  Listed rather
#: than inferred, so a typo at a call site still raises AttributeError
#: there instead of quietly parsing the census and then failing on a dict
#: lookup with a different name in the message.
_LAZY_NAMES = (
    "API_FUNCTIONS", "NAMESPACE_METHODS", "NAMESPACES", "BY_QUALIFIED_NAME",
)


def __getattr__(name: str):
    if name in _LAZY_NAMES:
        return _tables()[name]
    raise AttributeError("module %r has no attribute %r" % (__name__, name))


def __dir__() -> list:
    return sorted(list(globals()) + list(_LAZY_NAMES))


#: Declared, not inferred: `from ... import *` reads `__dict__` and never
#: calls `__dir__`, so without this a star-import of this module handed out
#: `Path`, `threading`, `dataclass` and `VendoredDataError` and none of the
#: four names the module exists to publish (pf-adversary, round `oghyca`).
__all__ = list(_LAZY_NAMES) + [
    "ApiFunction", "BODY_DIGEST_PREFIX", "body_digest",
]
