"""The 160-name server API surface the game's own Lua scripts call.

WHERE THIS COMES FROM.  ``api_spec.tsv`` beside this file is a frozen copy of
five columns (namespace, method, call_count, file_count, arity_min,
arity_max) taken from ``pf_bridge/gamedata/PF_GAMEDATA_LUA_API.tsv`` on
2026-09-05, which is itself generated by ``gamedata/pf_lua_api_census.py``
scanning the 616 shipped ``.lua`` files.  That census is LANE-Q's charter
(``prompts/LANE-Q.md``); this module is the vendored, dependency-free copy a
fresh clone of THIS repository needs so tests here never require a sibling
``pf_bridge`` checkout to know the shape of the API surface.

Nothing here is copied by hand: every row is one line straight out of the
TSV, so a re-vendor is a diff, not a retype.  If the count drifts (a new
game script pass finds more callers, or a rescan changes an arity), this
file's own count assertions in ``tests/test_script_lua_api_spec.py`` will
say so on the very next run, on any machine, without a sibling checkout.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .vendored import VendoredDataError

_SPEC_PATH = Path(__file__).with_name("api_spec.tsv")

#: The header this module was written against, in order.
_HEADER = (
    "namespace", "method", "call_count", "file_count",
    "arity_min", "arity_max",
)


@dataclass(frozen=True)
class ApiFunction:
    namespace: str
    method: str
    call_count: int
    file_count: int
    arity_min: int
    arity_max: int

    @property
    def qualified_name(self) -> str:
        return "%s.%s" % (self.namespace, self.method)


def _load() -> tuple[ApiFunction, ...]:
    """Parse ``api_spec.tsv``, refusing loudly on anything it is not.

    RAISES, NEVER ASSERTS (pf-adversary D13, round ``wn088m``).  The header
    check used to be a bare ``assert``, which ``python -O`` DELETES: under
    ``-O`` a re-vendor that reordered the columns would have been parsed
    happily, silently swapping ``call_count`` with ``file_count`` for all
    160 rows -- the guard would not have failed, it would not have existed.
    Every refusal here names the file and, where there is one, the line.

    :class:`~lua_api.vendored.VendoredDataError` rather than a bespoke
    class, so ``script_host`` classifies a corrupt mirror of OURS as
    ``LUA_HOST`` against this checkout instead of ``LUA_SCRIPT`` against
    whichever quest file was loading when the import happened.
    """
    try:
        text = _SPEC_PATH.read_text(encoding="ascii")
    except OSError as exc:
        raise VendoredDataError(
            "cannot read %s: %s" % (_SPEC_PATH, exc)) from exc
    except UnicodeDecodeError as exc:
        raise VendoredDataError(
            "%s is not ASCII: %s" % (_SPEC_PATH, exc)) from exc
    lines = text.splitlines()
    if not lines:
        raise VendoredDataError("%s is empty" % (_SPEC_PATH,))
    header = tuple(lines[0].split("\t"))
    if header != _HEADER:
        raise VendoredDataError(
            "%s header drifted: got %r, want %r"
            % (_SPEC_PATH, header, _HEADER))
    out = []
    for lineno, line in enumerate(lines[1:], start=2):
        if not line:
            continue
        cells = line.split("\t")
        if len(cells) != len(_HEADER):
            raise VendoredDataError(
                "%s line %d has %d columns, want %d: %r"
                % (_SPEC_PATH, lineno, len(cells), len(_HEADER), line))
        ns, method, call_count, file_count, arity_min, arity_max = cells
        try:
            numbers = [int(cell) for cell in
                       (call_count, file_count, arity_min, arity_max)]
        except ValueError as exc:
            raise VendoredDataError(
                "%s line %d has a non-integer count: %r"
                % (_SPEC_PATH, lineno, line)) from exc
        out.append(ApiFunction(
            namespace=ns,
            method=method,
            call_count=numbers[0],
            file_count=numbers[1],
            arity_min=numbers[2],
            arity_max=numbers[3],
        ))
    if not out:
        raise VendoredDataError("%s has a header and no rows" % (_SPEC_PATH,))
    return tuple(out)


#: Every row of the frozen census, in file order (namespace, then method).
API_FUNCTIONS: tuple[ApiFunction, ...] = _load()

#: namespace -> frozenset of its method names, e.g. NAMESPACE_METHODS["Quest"].
NAMESPACE_METHODS: dict[str, frozenset[str]] = {}
for _fn in API_FUNCTIONS:
    NAMESPACE_METHODS.setdefault(_fn.namespace, set()).add(_fn.method)
NAMESPACE_METHODS = {k: frozenset(v) for k, v in NAMESPACE_METHODS.items()}

#: The 8 namespace names the game's scripts index as Lua globals.
NAMESPACES: tuple[str, ...] = tuple(sorted(NAMESPACE_METHODS))

#: qualified name ("Quest.SetFlag") -> ApiFunction, for lookup by call site.
BY_QUALIFIED_NAME: dict[str, ApiFunction] = {
    fn.qualified_name: fn for fn in API_FUNCTIONS
}
